var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},h),ba=[],ca="./this.program",da=(a,b)=>{throw b;},k="",ea,fa;"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src);k=0!==k.indexOf("blob:")?k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1):"";ea=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};
fa=a=>{document.title=a};var ha=h.print||console.log.bind(console),l=h.printErr||console.warn.bind(console);Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);h.quit&&(da=h.quit);var ia;h.wasmBinary&&(ia=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!=typeof WebAssembly&&p("no native wasm support detected");var ja,q=!1,ka,u,w,la,ma,x,y,z,A,na,oa=[],qa=[],ra=[],sa=[],ta=[];function ua(){var a=h.preRun.shift();oa.unshift(a)}var B=0,va=null,wa=null;
function p(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";l(a);q=!0;ka=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function xa(a){return a.startsWith("data:application/octet-stream;base64,")}var C;C="index.wasm";if(!xa(C)){var ya=C;C=h.locateFile?h.locateFile(ya,k):k+ya}function za(a){try{if(a==C&&ia)return new Uint8Array(ia);throw"both async and sync fetching of the wasm failed";}catch(b){p(b)}}
function Aa(a){return ia||"function"!=typeof fetch?Promise.resolve().then(()=>za(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>za(a))}function Ba(a,b,c){return Aa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{l("failed to asynchronously prepare wasm: "+d);p(d)})}
function Ca(a,b){var c=C;ia||"function"!=typeof WebAssembly.instantiateStreaming||xa(c)||"function"!=typeof fetch?Ba(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){l("wasm streaming compile failed: "+e);l("falling back to ArrayBuffer instantiation");return Ba(c,a,b)}))}
var Da,Ea,Ia={87601:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,87748:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,87982:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.fe||("undefined"!==typeof AudioContext?b.fe=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.fe=new webkitAudioContext),b.fe&&
Fa(b.fe));return void 0===b.fe?-1:0},88475:()=>h.SDL2.fe.sampleRate,88543:(a,b,c,d)=>{function e(){}function g(m){void 0!==f.capture.re&&(clearTimeout(f.capture.re),f.capture.re=void 0);f.capture.ye=f.fe.createMediaStreamSource(m);f.capture.he=f.fe.createScriptProcessor(b,a,1);f.capture.he.onaudioprocess=function(n){void 0!==f&&void 0!==f.capture&&(n.outputBuffer.getChannelData(0).fill(0),f.capture.Be=n.inputBuffer,Ga(c,[d]))};f.capture.ye.connect(f.capture.he);f.capture.he.connect(f.fe.destination);
f.capture.stream=m}var f=h.SDL2;f.capture.ze=f.fe.createBuffer(a,b,f.fe.sampleRate);f.capture.ze.getChannelData(0).fill(0);f.capture.re=setTimeout(function(){f.capture.Be=f.capture.ze;Ga(c,[d])},b/f.fe.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(g).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},g,e)},90195:(a,b,c,d)=>{var e=h.SDL2;e.audio.he=
e.fe.createScriptProcessor(b,0,a);e.audio.he.onaudioprocess=function(g){void 0!==e&&void 0!==e.audio&&(e.audio.He=g.outputBuffer,Ga(c,[d]))};e.audio.he.connect(e.fe.destination)},90605:(a,b)=>{for(var c=h.SDL2,d=c.capture.Be.numberOfChannels,e=0;e<d;++e){var g=c.capture.Be.getChannelData(e);if(g.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";if(1==d)for(var f=0;f<b;++f)Ha(a+4*f,g[f]);else for(f=0;f<b;++f)Ha(a+4*(f*d+e),
g[f])}},91210:(a,b)=>{for(var c=h.SDL2,d=c.audio.He.numberOfChannels,e=0;e<d;++e){var g=c.audio.He.getChannelData(e);if(g.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";for(var f=0;f<b;++f)g[f]=z[a+(f*d+e<<2)>>2]}},91690:a=>{var b=h.SDL2;if(a){void 0!==b.capture.re&&clearTimeout(b.capture.re);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=
void 0}void 0!==b.capture.he&&(b.capture.he.onaudioprocess=function(){},b.capture.he.disconnect(),b.capture.he=void 0);void 0!==b.capture.ye&&(b.capture.ye.disconnect(),b.capture.ye=void 0);void 0!==b.capture.ze&&(b.capture.ze=void 0);b.capture=void 0}else void 0!=b.audio.he&&(b.audio.he.disconnect(),b.audio.he=void 0),b.audio=void 0;void 0!==b.fe&&void 0===b.audio&&void 0===b.capture&&(b.fe.close(),b.fe=void 0)},92862:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Pe!==h.canvas&&(d.le=h.createContext(h.canvas,
!1,!0),d.Pe=h.canvas);if(d.w!==a||d.Ze!==b||d.bf!==d.le)d.image=d.le.createImageData(a,b),d.w=a,d.Ze=b,d.bf=d.le;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var g=x[b];a[e]=g&255;a[e+1]=g>>8&255;a[e+2]=g>>16&255;a[e+3]=255;b++;e+=4}else if(d.Se!==a&&(d.Re=new Int32Array(a.buffer),d.Te=new Uint8Array(a.buffer),d.Se=a),a=d.Re,c=a.length,a.set(x.subarray(b,b+c)),a=d.Te,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,
b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.le.putImageData(d.image,0,0)},94331:(a,b,c,d,e)=>{var g=document.createElement("canvas");g.width=a;g.height=b;var f=g.getContext("2d");a=f.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var r=x[e];b[m]=r&255;b[m+1]=r>>8&255;b[m+2]=r>>16&255;b[m+3]=r>>24&255;e++;m+=
4}else b=new Int32Array(b.buffer),n=b.length,b.set(x.subarray(e,e+n));f.putImageData(a,0,0);c=0===c&&0===d?"url("+g.toDataURL()+"), auto":"url("+g.toDataURL()+") "+c+" "+d+", auto";d=D(c.length+1);E(c,d,c.length+1);return d},95320:a=>{h.canvas&&(h.canvas.style.cursor=F(a))},95403:()=>{h.canvas&&(h.canvas.style.cursor="none")},95472:()=>window.innerWidth,95502:()=>window.innerHeight};function Ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function Ka(a,b,c){a.addEventListener(b,c,{once:!0})}function Fa(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&Ka(d,c,()=>{"suspended"===a.state&&a.resume()})})})}function La(a){for(;0<a.length;)a.shift()(h)}var Ma=[];function G(a){var b=Ma[a];b||(a>=Ma.length&&(Ma.length=a+1),Ma[a]=b=na.get(a));return b}
function Ga(a,b){if("vi".includes("j")){var c=h.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else G(a).apply(null,b)}
function Ha(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":u[a>>0]=b;break;case "i8":u[a>>0]=b;break;case "i16":la[a>>1]=b;break;case "i32":x[a>>2]=b;break;case "i64":Ea=[b>>>0,(Da=b,1<=+Math.abs(Da)?0<Da?+Math.floor(Da/4294967296)>>>0:~~+Math.ceil((Da-+(~~Da>>>0))/4294967296)>>>0:0)];x[a>>2]=Ea[0];x[a+4>>2]=Ea[1];break;case "float":z[a>>2]=b;break;case "double":A[a>>3]=b;break;case "*":y[a>>2]=b;break;default:p("invalid type for setValue: "+c)}}
var Na="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Oa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Na)return Na.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function F(a,b){return a?Oa(w,a,b):""}
function Pa(a,b){Qa=a;Ra=b;if(Sa)if(Ta||(Ta=!0),0==a)H=function(){var d=Math.max(0,Ua+b-Va())|0;setTimeout(Wa,d)};else if(1==a)H=function(){Xa(Wa)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}H=function(){setImmediate(Wa)}}}var Va;Va=()=>performance.now();
function Ya(a,b,c,d,e){!Sa||p("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Sa=a;Za=d;var g=$a;Ta=!1;Wa=function(){if(!q)if(0<ab.length){var f=Date.now(),m=ab.shift();m.mf(m.hf);if(bb){var n=bb,r=0==n%1?n-1:Math.floor(n);bb=m.kf?r:(8*n+(r+.5))/9}ha('main loop blocker "'+m.name+'" took '+(Date.now()-f)+" ms");h.setStatus&&(f=h.statusMessage||"Please wait...",
m=bb,n=cb.lf,m?m<n?h.setStatus(f+" ("+(n-m)+"/"+n+")"):h.setStatus(f):h.setStatus(""));g<$a||setTimeout(Wa,0)}else g<$a||(db=db+1|0,1==Qa&&1<Ra&&0!=db%Ra?H():(0==Qa&&(Ua=Va()),q||h.preMainLoop&&!1===h.preMainLoop()||(eb(a),h.postMainLoop&&h.postMainLoop()),g<$a||("object"==typeof SDL&&SDL.audio&&SDL.audio.df&&SDL.audio.df(),H())))};e||(b&&0<b?Pa(0,1E3/b):Pa(1,1),H());if(c)throw"unwind";}function fb(a){a instanceof Ja||"unwind"==a||da(1,a)}
function gb(a){ka=ka=a;if(!noExitRuntime){if(h.onExit)h.onExit(a);q=!0}da(a,new Ja(a))}function eb(a){if(!q)try{if(a(),!noExitRuntime)try{gb(ka)}catch(b){fb(b)}}catch(b){fb(b)}}function hb(a){setTimeout(()=>{eb(a)},1E4)}function ib(a){jb||(jb={});jb[a]||(jb[a]=1,l(a))}var jb,Ta=!1,H=null,$a=0,Sa=null,Za=0,Qa=0,Ra=0,db=0,ab=[],cb={},Ua,Wa,bb,kb=!1,mb=!1,nb=[];
function ob(){function a(){mb=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!pb){pb=!0;try{qb=!0}catch(c){qb=!1,l("warning: no blob constructor, cannot create blobs with mimetypes")}rb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:qb?null:l("warning: no BlobBuilder");sb="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;h.Ke||"undefined"!=typeof sb||(l("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.Ke=!0);h.preloadPlugins.push({canHandle:function(c){return!h.Ke&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var f=null;if(qb)try{f=new Blob([c],{type:tb(d)}),f.size!==c.length&&(f=new Blob([(new Uint8Array(c)).buffer],{type:tb(d)}))}catch(r){ib("Blob constructor present but fails: "+
r+"; falling back to blob builder")}f||(f=new rb,f.append((new Uint8Array(c)).buffer),f=f.getBlob());var m=sb.createObjectURL(f),n=new Image;n.onload=()=>{n.complete||p("Image "+d+" could not be decoded");var r=document.createElement("canvas");r.width=n.width;r.height=n.height;r.getContext("2d").drawImage(n,0,0);sb.revokeObjectURL(m);e&&e(c)};n.onerror=()=>{ha("Image "+m+" could not be decoded");g&&g()};n.src=m}});h.preloadPlugins.push({canHandle:function(c){return!h.sf&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,d,e,g){function f(){n||(n=!0,e&&e(c))}function m(){n||(n=!0,new Audio,g&&g())}var n=!1;if(qb){try{var r=new Blob([c],{type:tb(d)})}catch(v){return m()}r=sb.createObjectURL(r);var t=new Audio;t.addEventListener("canplaythrough",()=>f(t),!1);t.onerror=function(){if(!n){l("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var v="",N=0,J=0,pa=0;pa<c.length;pa++)for(N=N<<8|c[pa],J+=8;6<=J;){var lb=N>>J-6&63;J-=6;v+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[lb]}2==
J?(v+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(N&3)<<4],v+="=="):4==J&&(v+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(N&15)<<2],v+="=");t.src="data:audio/x-"+d.substr(-3)+";base64,"+v;f(t)}};t.src=r;hb(()=>{f(t)})}else return m()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!mb&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function ub(a,b,c,d){if(b&&h.le&&a==h.canvas)return h.le;var e;if(b){var g={antialias:!1,alpha:!1,Je:1};if(d)for(var f in d)g[f]=d[f];if("undefined"!=typeof vb&&(e=wb(a,g)))var m=I[e].ne}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof K||p("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.le=m,b&&xb(e),h.ff=b,nb.forEach(n=>n()),ob());return m}var yb=!1,zb=void 0,Ab=void 0;
function Bb(a,b){function c(){kb=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Cb,zb&&d.requestPointerLock(),kb=!0,Ab?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]|8388608),Db(h.canvas),Eb()):Db(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),Ab?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]&
-8388609),Db(h.canvas),Eb()):Db(d));if(h.onFullScreen)h.onFullScreen(kb);if(h.onFullscreen)h.onFullscreen(kb)}zb=a;Ab=b;"undefined"==typeof zb&&(zb=!0);"undefined"==typeof Ab&&(Ab=!1);var d=h.canvas;yb||(yb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Cb(){if(!kb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Fb=0;function Xa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Fb)Fb=b+1E3/60;else for(;b+2>=Fb;)Fb+=1E3/60;setTimeout(a,Math.max(Fb-b,0))}}
function tb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Gb=[];function Eb(){var a=h.canvas;Gb.forEach(b=>b(a.width,a.height))}
function Db(a,b,c){b&&c?(a.gf=b,a.af=c):(b=a.gf,c=a.af);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}Ab?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var pb,qb,rb,sb,L=12288,Hb=!1,Ib=0,Jb=0,Kb=0,M={alpha:!1,depth:!1,stencil:!1,antialias:!1},Lb={},Mb;function Nb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,g){b.drawArraysInstancedANGLE(c,d,e,g)},a.drawElementsInstanced=function(c,d,e,g,f){b.drawElementsInstancedANGLE(c,d,e,g,f)})}
function Ob(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Pb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Qb=1,Rb=[],O=[],Sb=[],Tb=[],Ub=[],P=[],Vb=[],I=[],Q=[],Wb={},Xb=4;
function R(a){Yb||(Yb=a)}function Zb(a){for(var b=Qb++,c=a.length;c<b;c++)a[c]=null;return b}function wb(a,b){a.ue||(a.ue=a.getContext,a.getContext=function(d,e){e=a.ue(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?$b(c,b):0}function $b(a,b){var c=Zb(I),d={nf:c,attributes:b,version:b.Je,ne:a};a.canvas&&(a.canvas.qe=d);I[c]=d;("undefined"==typeof b.Ve||b.Ve)&&ac(d);return c}function xb(a){bc=I[a];h.le=K=bc&&bc.ne}
function ac(a){a||(a=bc);if(!a.cf){a.cf=!0;var b=a.ne;Nb(b);Ob(b);Pb(b);b.me=b.getExtension("EXT_disjoint_timer_query");b.rf=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var vb={},Yb,bc;function cc(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}
function E(a,b,c){var d=w;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.charCodeAt(g);if(55296<=f&&57343>=f){var m=a.charCodeAt(++g);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e}function S(a){var b=cc(a)+1,c=D(b);c&&E(a,c,b);return c}var dc=[];
function ec(a,b){dc.length=0;var c;for(b>>=2;c=w[a++];)b+=105!=c&b,dc.push(105==c?x[b]:A[b++>>1]),++b;return dc}function fc(a,b,c){ea(a,d=>{d||p('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(d))},()=>{if(c)c();else throw'Loading data file "'+a+'" failed.';})}function gc(a){var b=hc();a=a();ic(b);return a}var jc=0;function kc(){for(var a=T.length-1;0<=a;--a)lc(a);T=[];U=[]}var U=[];
function mc(a,b,c){function d(f,m){if(f.length!=m.length)return!1;for(var n in f)if(f[n]!=m[n])return!1;return!0}for(var e in U){var g=U[e];if(g.De==a&&d(g.Fe,c))return}U.push({De:a,Me:b,Fe:c});U.sort(function(f,m){return f.Me<m.Me})}function nc(a){for(var b=0;b<U.length;++b)U[b].De==a&&(U.splice(b,1),--b)}function oc(){if(jc&&pc.pe)for(var a=0;a<U.length;++a){var b=U[a];U.splice(a,1);--a;b.De.apply(null,b.Fe)}}var T=[];
function lc(a){var b=T[a];b.target.removeEventListener(b.ge,b.We,b.ie);T.splice(a,1)}function V(a){function b(d){++jc;pc=a;oc();a.ke(d);oc();--jc}if(a.je)a.We=b,a.target.addEventListener(a.ge,b,a.ie),T.push(a),qc||(sa.push(kc),qc=!0);else for(var c=0;c<T.length;++c)T[c].target==a.target&&T[c].ge==a.ge&&lc(c--)}function rc(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function sc(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var tc={},qc,pc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc={},Hc=[0,document,window];function W(a){a=2<a?F(a):a;return Hc[a]||document.querySelector(a)}function Ic(a){var b=cc(a)+1,c=Jc(b);E(a,c,b);return c}function Kc(a){return gc(function(){var b=Jc(8),c=b+4,d=Ic(a.id);if(d=W(d))x[b>>2]=d.width,x[c>>2]=d.height;return[x[b>>2],x[c>>2]]})}function Lc(a,b,c){a=W(a);if(!a)return-4;a.width=b;a.height=c;return 0}function Mc(a,b,c){a.jf?gc(function(){var d=Ic(a.id);Lc(d,b,c)}):(a.width=b,a.height=c)}
function Nc(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Mc(a,d,e),a.style.width=g,a.style.height=f,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=r,a.style.paddingRight=t,a.style.paddingTop=v,a.style.paddingBottom=N,a.style.marginLeft=J,a.style.marginRight=pa,a.style.marginTop=
lb,a.style.marginBottom=Zd,document.body.style.margin=$d,document.documentElement.style.overflow=ae,document.body.scroll=be,a.style.oe=ce,a.qe&&a.qe.ne.viewport(0,0,d,e),Gc.te&&G(Gc.te)(37,0,Gc.Ge))}var c=Kc(a),d=c[0],e=c[1],g=a.style.width,f=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,r=a.style.paddingLeft,t=a.style.paddingRight,v=a.style.paddingTop,N=a.style.paddingBottom,J=a.style.marginLeft,pa=a.style.marginRight,lb=a.style.marginTop,Zd=a.style.marginBottom,
$d=document.body.style.margin,ae=document.documentElement.style.overflow,be=document.body.scroll,ce=a.style.oe;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function Oc(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function Pc(a){return 0>Hc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Qc(a,b){if(0!=b.Ce||0!=b.Ae){Nc(a);var c=b.ef?innerWidth:screen.width,d=b.ef?innerHeight:screen.height,e=Pc(a),g=e.width;e=e.height;var f=Kc(a),m=f[0];f=f[1];3==b.Ce?(Oc(a,(d-e)/2,(c-g)/2),c=g,d=e):2==b.Ce&&(c*f<m*d?(g=f*c/m,Oc(a,(d-g)/2,0),d=g):(g=m*d/f,Oc(a,0,(c-g)/2),c=g));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Xe&&(a.style.oe="optimizeSpeed",
a.style.oe="-moz-crisp-edges",a.style.oe="-o-crisp-edges",a.style.oe="-webkit-optimize-contrast",a.style.oe="optimize-contrast",a.style.oe="crisp-edges",a.style.oe="pixelated");g=2==b.Ae?devicePixelRatio:1;0!=b.Ae&&(c=c*g|0,d=d*g|0,Mc(a,c,d),a.qe&&a.qe.ne.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return sc()?-3:-1;Gc=b;b.te&&G(b.te)(37,0,b.Ge);return 0}
function Rc(a){if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0}
function Sc(a,b){A[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)A[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)A[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)x[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];x[a+1296>>2]=b.connected;x[a+1300>>2]=b.index;x[a+8>>2]=b.axes.length;x[a+12>>2]=b.buttons.length;E(b.id,a+1304,64);E(b.mapping,a+1368,64)}function Tc(a,b){K.attachShader(O[a],P[b])}
function Uc(a,b){K.bindBuffer(a,Rb[b])}function Vc(a){K.blendEquation(a)}function Wc(a,b){K.blendFunc(a,b)}function Xc(a,b,c,d){K.bufferData(a,c?w.subarray(c,c+b):b,d)}function Yc(a){K.clear(a)}function Zc(a,b,c,d){K.clearColor(a,b,c,d)}function $c(a){K.compileShader(P[a])}function ad(){var a=Zb(O),b=K.createProgram();b.name=a;b.xe=b.ve=b.we=0;b.Ee=1;O[a]=b;return a}function bd(a){var b=Zb(P);P[b]=K.createShader(a);return b}
function cd(a){if(a){var b=O[a];b?(K.deleteProgram(b),b.name=0,O[a]=null):R(1281)}}function dd(a){K.disable(a)}function ed(a){K.disableVertexAttribArray(a)}var fd=[];function gd(a,b,c,d){K.drawElements(a,b,c,d)}function hd(a){K.enable(a)}function jd(a){K.enableVertexAttribArray(a)}function kd(a,b,c,d){for(var e=0;e<a;e++){var g=K[c](),f=g&&Zb(d);g?(g.name=f,d[f]=g):R(1282);x[b+4*e>>2]=f}}function ld(a,b){kd(a,b,"createBuffer",Rb)}
function md(a,b,c,d,e,g,f,m){b=O[b];if(a=K[a](b,c))d=m&&E(a.name,m,d),e&&(x[e>>2]=d),g&&(x[g>>2]=a.size),f&&(x[f>>2]=a.type)}function nd(a,b){return K.getAttribLocation(O[a],F(b))}function od(a,b){y[a>>2]=b;y[a+4>>2]=(b-y[a>>2])/4294967296}
function pd(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&R(1280);return;case 36345:d=0;break;case 34466:var e=K.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=K.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":R(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:R(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:x[b+4*a>>2]=e[a];break;case 2:z[b+4*a>>2]=e[a];break;case 4:u[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(g){R(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:R(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:od(b,
d);break;case 0:x[b>>2]=d;break;case 2:z[b>>2]=d;break;case 4:u[b>>0]=d?1:0}}else R(1281)}function qd(a,b,c,d){a=K.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,d,b):0;c&&(x[c>>2]=b)}
function rd(a,b,c){if(c)if(a>=Qb)R(1281);else if(a=O[a],35716==b)a=K.getProgramInfoLog(a),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b){if(!a.xe)for(b=0;b<K.getProgramParameter(a,35718);++b)a.xe=Math.max(a.xe,K.getActiveUniform(a,b).name.length+1);x[c>>2]=a.xe}else if(35722==b){if(!a.ve)for(b=0;b<K.getProgramParameter(a,35721);++b)a.ve=Math.max(a.ve,K.getActiveAttrib(a,b).name.length+1);x[c>>2]=a.ve}else if(35381==b){if(!a.we)for(b=0;b<K.getProgramParameter(a,35382);++b)a.we=
Math.max(a.we,K.getActiveUniformBlockName(a,b).length+1);x[c>>2]=a.we}else x[c>>2]=K.getProgramParameter(a,b);else R(1281)}function sd(a,b,c){if(c){a=K.me.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;od(c,d)}else R(1281)}function td(a,b,c){if(c){a=K.me.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else R(1281)}function ud(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}
function vd(a){var b=a.se,c=a.Oe,d;if(!b)for(a.se=b={},a.Ne={},d=0;d<K.getProgramParameter(a,35718);++d){var e=K.getActiveUniform(a,d);var g=e.name;e=e.size;var f=ud(g);f=0<f?g.slice(0,f):g;var m=a.Ee;a.Ee+=e;c[f]=[e,m];for(g=0;g<e;++g)b[m]=g,a.Ne[m++]=f}}function wd(a,b){b=F(b);if(a=O[a]){vd(a);var c=a.se,d=0,e=b,g=ud(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Oe[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||K.getUniformLocation(a,b)))return d}else R(1281);return-1}
function X(a){var b=K.Qe;if(b){var c=b.se[a];"number"==typeof c&&(b.se[a]=c=K.getUniformLocation(b,b.Ne[a]+(0<c?"["+c+"]":"")));return c}R(1282)}function xd(a,b,c,d){if(c)if(a=O[a],vd(a),a=K.getUniform(a,X(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:z[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b]}else R(1281)}
function yd(a,b,c,d){if(c)if(a=K.getVertexAttrib(a,b),34975==b)x[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:z[c>>2]=a;break;case 5:x[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b];break;case 5:x[c+4*b>>2]=Math.fround(a[b])}else R(1281)}function zd(a){a=O[a];K.linkProgram(a);a.se=0;a.Oe={}}
function Ad(a,b,c,d,e){a-=5120;a=1==a?w:4==a?x:6==a?z:5==a||28922==a?y:ma;var g=31-Math.clz32(a.BYTES_PER_ELEMENT),f=Xb;return a.subarray(e>>g,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<g)+f-1&-f)>>g)}function Bd(a,b,c,d){for(var e="",g=0;g<b;++g){var f=d?x[d+4*g>>2]:-1;e+=F(x[c+4*g>>2],0>f?void 0:f)}K.shaderSource(P[a],e)}function Cd(a,b){K.uniform1f(X(a),b)}var Y=[],Dd=[];function Ed(a,b,c,d){K.uniform3f(X(a),b,c,d)}
function Fd(a,b,c,d){if(18>=b){var e=Y[16*b-1],g=z;d>>=2;for(var f=0;f<16*b;f+=16){var m=d+f;e[f]=g[m];e[f+1]=g[m+1];e[f+2]=g[m+2];e[f+3]=g[m+3];e[f+4]=g[m+4];e[f+5]=g[m+5];e[f+6]=g[m+6];e[f+7]=g[m+7];e[f+8]=g[m+8];e[f+9]=g[m+9];e[f+10]=g[m+10];e[f+11]=g[m+11];e[f+12]=g[m+12];e[f+13]=g[m+13];e[f+14]=g[m+14];e[f+15]=g[m+15]}}else e=z.subarray(d>>2,d+64*b>>2);K.uniformMatrix4fv(X(a),!!c,e)}function Gd(a){a=O[a];K.useProgram(a);K.Qe=a}function Hd(a,b,c,d,e,g){K.vertexAttribPointer(a,b,c,!!d,e,g)}
function Id(a,b,c,d){K.viewport(a,b,c,d)}function Jd(a,b){if(!sc())return-1;a=W(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?jc&&pc.pe?Qc(a,b):b.Ue?(mc(Qc,1,[a,b]),1):-2:-3:-4}function Kd(a,b){var c={target:W(2),ge:"beforeunload",je:b,ke:function(d=event){var e=G(b)(28,0,a);e&&(e=F(e));if(e)return d.preventDefault(),d.returnValue=e},ie:!0};V(c)}
function Ld(a,b,c,d,e,g){vc||(vc=D(256));a={target:W(a),ge:g,je:d,ke:function(f=event){var m=f.target.id?f.target.id:"",n=vc;E(rc(f.target),n+0,128);E(m,n+128,128);G(d)(e,n,b)&&f.preventDefault()},ie:c};V(a)}
function Md(a,b,c,d,e){xc||(xc=D(280));V({target:a,ge:e,je:d,ke:function(g=event){var f=xc,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;x[f>>2]=n;x[f+4>>2]=sc();var r=n?m:wc,t=r&&r.id?r.id:"";E(rc(r),f+8,128);E(t,f+136,128);x[f+264>>2]=r?r.clientWidth:0;x[f+268>>2]=r?r.clientHeight:0;x[f+272>>2]=screen.width;x[f+276>>2]=screen.height;n&&(wc=m);G(d)(19,f,b)&&g.preventDefault()},ie:c})}
function Nd(a,b,c,d,e){yc||(yc=D(1432));b={target:W(2),pe:!0,ge:e,je:c,ke:function(g=event){var f=yc;Sc(f,g.gamepad);G(c)(d,f,a)&&g.preventDefault()},ie:b};V(b)}
function Od(a,b,c,d,e,g){zc||(zc=D(176));a={target:W(a),pe:!0,ge:g,je:d,ke:function(f){var m=zc;A[m>>3]=f.timeStamp;var n=m>>2;x[n+2]=f.location;x[n+3]=f.ctrlKey;x[n+4]=f.shiftKey;x[n+5]=f.altKey;x[n+6]=f.metaKey;x[n+7]=f.repeat;x[n+8]=f.charCode;x[n+9]=f.keyCode;x[n+10]=f.which;E(f.key||"",m+44,32);E(f.code||"",m+76,32);E(f.char||"",m+108,32);E(f.locale||"",m+140,32);G(d)(e,m,b)&&f.preventDefault()},ie:c};V(a)}
function Pd(a,b,c){A[a>>3]=b.timeStamp;a>>=2;x[a+2]=b.screenX;x[a+3]=b.screenY;x[a+4]=b.clientX;x[a+5]=b.clientY;x[a+6]=b.ctrlKey;x[a+7]=b.shiftKey;x[a+8]=b.altKey;x[a+9]=b.metaKey;la[2*a+20]=b.button;la[2*a+21]=b.buttons;x[a+11]=b.movementX;x[a+12]=b.movementY;c=Pc(c);x[a+13]=b.clientX-c.left;x[a+14]=b.clientY-c.top}
function Qd(a,b,c,d,e,g){Ac||(Ac=D(72));a=W(a);V({target:a,pe:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,ge:g,je:d,ke:function(f=event){Pd(Ac,f,a);G(d)(e,Ac,b)&&f.preventDefault()},ie:c})}function Rd(a,b,c,d,e){Bc||(Bc=D(260));V({target:a,ge:e,je:d,ke:function(g=event){var f=Bc,m=document.pointerLockElement||document.ue||document.$e||document.Ye;x[f>>2]=!!m;var n=m&&m.id?m.id:"";E(rc(m),f+4,128);E(n,f+132,128);G(d)(20,f,b)&&g.preventDefault()},ie:c})}
function Sd(a,b,c,d){Cc||(Cc=D(36));a=W(a);V({target:a,ge:"resize",je:d,ke:function(e=event){if(e.target==a){var g=document.body;if(g){var f=Cc;x[f>>2]=e.detail;x[f+4>>2]=g.clientWidth;x[f+8>>2]=g.clientHeight;x[f+12>>2]=innerWidth;x[f+16>>2]=innerHeight;x[f+20>>2]=outerWidth;x[f+24>>2]=outerHeight;x[f+28>>2]=pageXOffset;x[f+32>>2]=pageYOffset;G(d)(10,f,b)&&e.preventDefault()}}},ie:c})}
function Td(a,b,c,d,e,g){Dc||(Dc=D(1696));a=W(a);V({target:a,pe:"touchstart"==g||"touchend"==g,ge:g,je:d,ke:function(f){for(var m,n={},r=f.touches,t=0;t<r.length;++t)m=r[t],m.Ie=m.Le=0,n[m.identifier]=m;for(t=0;t<f.changedTouches.length;++t)m=f.changedTouches[t],m.Ie=1,n[m.identifier]=m;for(t=0;t<f.targetTouches.length;++t)n[f.targetTouches[t].identifier].Le=1;r=Dc;A[r>>3]=f.timeStamp;var v=r>>2;x[v+3]=f.ctrlKey;x[v+4]=f.shiftKey;x[v+5]=f.altKey;x[v+6]=f.metaKey;v+=7;var N=Pc(a),J=0;for(t in n)if(m=
n[t],x[v]=m.identifier,x[v+1]=m.screenX,x[v+2]=m.screenY,x[v+3]=m.clientX,x[v+4]=m.clientY,x[v+5]=m.pageX,x[v+6]=m.pageY,x[v+7]=m.Ie,x[v+8]=m.Le,x[v+9]=m.clientX-N.left,x[v+10]=m.clientY-N.top,v+=13,31<++J)break;x[r+8>>2]=J;G(d)(e,r,b)&&f.preventDefault()},ie:c})}
function Ud(a,b,c){var d=Hc[1];Ec||(Ec=D(8));V({target:d,ge:"visibilitychange",je:c,ke:function(e=event){var g=Ec,f=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);x[g>>2]=document.hidden;x[g+4>>2]=f;G(c)(21,g,a)&&e.preventDefault()},ie:b})}
function Vd(a,b,c,d){Fc||(Fc=D(104));V({target:a,pe:!0,ge:"wheel",je:d,ke:function(e=event){var g=Fc;Pd(g,e,a);A[g+72>>3]=e.deltaX;A[g+80>>3]=e.deltaY;A[g+88>>3]=e.deltaZ;x[g+96>>2]=e.deltaMode;G(d)(9,g,b)&&e.preventDefault()},ie:c})}var Wd={};
function Xd(){if(!Yd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Wd)void 0===Wd[b]?delete a[b]:a[b]=Wd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Yd=c}return Yd}var Yd,de=[null,[],[]];h.requestFullscreen=function(a,b){Bb(a,b)};h.requestAnimationFrame=function(a){Xa(a)};
h.setCanvasSize=function(a,b,c){Db(h.canvas,a,b);c||Eb()};h.pauseMainLoop=function(){H=null;$a++};h.resumeMainLoop=function(){$a++;var a=Qa,b=Ra,c=Sa;Sa=null;Ya(c,0,!1,Za,!0);Pa(a,b);H()};h.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=function(a,b,c,d){return ub(a,b,c,d)};for(var K,Z=0;32>Z;++Z)fd.push(Array(Z));var ee=new Float32Array(288);for(Z=0;288>Z;++Z)Y[Z]=ee.subarray(0,Z+1);
var fe=new Int32Array(288);for(Z=0;288>Z;++Z)Dd[Z]=fe.subarray(0,Z+1);
var he={_:function(){return 0},Ya:function(){return 0},Za:function(){},_a:function(){return!0},Fa:function(a){if(12448==a)return L=12288,1;L=12300;return 0},Ja:function(a,b,c,d,e){if(62E3!=a)L=12296,c=0;else{if(b)for(;;){a=x[b>>2];if(12321==a)M.alpha=0<x[b+4>>2];else if(12325==a)M.depth=0<x[b+4>>2];else if(12326==a)M.stencil=0<x[b+4>>2];else if(12337==a)a=x[b+4>>2],M.antialias=0<a;else if(12338==a)a=x[b+4>>2],M.antialias=1==a;else if(12544==a)M.pf=12547!=x[b+4>>2];else if(12344==a)break;b+=8}c&&d||
e?(e&&(x[e>>2]=1),c&&0<d&&(x[c>>2]=62002),L=12288,c=1):(L=12300,c=0)}return c},wa:function(a,b,c,d){if(62E3!=a)return L=12296,0;for(a=1;;){b=x[d>>2];if(12440==b)a=x[d+4>>2];else if(12344==b)break;else return L=12292,0;d+=8}if(2!=a)return L=12293,0;M.Je=a-1;M.qf=0;Mb=wb(h.canvas,M);if(0!=Mb)return L=12288,xb(Mb),h.ff=!0,nb.forEach(function(e){e()}),xb(null),62004;L=12297;return 0},ya:function(a,b){if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;L=12288;return 62006},xa:function(a,b){if(62E3!=
a)return L=12296,0;if(62004!=b)return L=12294,0;a=Mb;bc===I[a]&&(bc=null);if("object"==typeof tc)for(var c=I[a].ne.canvas,d=0;d<T.length;++d)T[d].target!=c||lc(d--);I[a]&&I[a].ne.canvas&&(I[a].ne.canvas.qe=void 0);I[a]=null;L=12288;Ib==b&&(Ib=0);return 1},za:function(a,b){if(62E3!=a)return L=12296,0;if(62006!=b)return L=12301,1;Jb==b&&(Jb=0);Kb==b&&(Kb=0);L=12288;return 1},Ka:function(a,b,c,d){if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;if(!d)return L=12300,0;L=12288;switch(c){case 12320:return x[d>>
2]=M.alpha?32:24,1;case 12321:return x[d>>2]=M.alpha?8:0,1;case 12322:return x[d>>2]=8,1;case 12323:return x[d>>2]=8,1;case 12324:return x[d>>2]=8,1;case 12325:return x[d>>2]=M.depth?24:0,1;case 12326:return x[d>>2]=M.stencil?8:0,1;case 12327:return x[d>>2]=12344,1;case 12328:return x[d>>2]=62002,1;case 12329:return x[d>>2]=0,1;case 12330:return x[d>>2]=4096,1;case 12331:return x[d>>2]=16777216,1;case 12332:return x[d>>2]=4096,1;case 12333:return x[d>>2]=0,1;case 12334:return x[d>>2]=0,1;case 12335:return x[d>>
2]=12344,1;case 12337:return x[d>>2]=M.antialias?4:0,1;case 12338:return x[d>>2]=M.antialias?1:0,1;case 12339:return x[d>>2]=4,1;case 12340:return x[d>>2]=12344,1;case 12341:case 12342:case 12343:return x[d>>2]=-1,1;case 12345:case 12346:return x[d>>2]=0,1;case 12347:return x[d>>2]=0,1;case 12348:return x[d>>2]=1;case 12349:case 12350:return x[d>>2]=0,1;case 12351:return x[d>>2]=12430,1;case 12352:return x[d>>2]=4,1;case 12354:return x[d>>2]=0,1;default:return L=12292,0}},Q:function(){L=12288;return 62E3},
va:function(){return L},Ha:function(a,b,c){if(62E3!=a)return L=12296,0;b&&(x[b>>2]=1);c&&(x[c>>2]=4);Hb=!0;L=12288;return 1},Aa:function(a,b,c,d){if(62E3!=a)return L=12296,0;if(0!=d&&62004!=d)return L=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return L=12301,0;xb(d?Mb:null);Ib=d;Kb=b;Jb=c;L=12288;return 1},ua:function(a,b){if(62E3!=a)return L=12296,0;L=12288;if(Lb[b])return Lb[b];switch(b){case 12371:a=S("Emscripten");break;case 12372:a=S("1.4 Emscripten EGL");break;case 12373:a=S("");break;case 12429:a=
S("OpenGL_ES");break;default:return L=12300,0}return Lb[b]=a},Ba:function(){if(Hb)if(h.le)if(h.le.isContextLost())L=12302;else return L=12288,1;else L=12290;else L=12289;return 0},Ca:function(a,b){if(62E3!=a)return L=12296,0;0==b?Pa(0,0):Pa(1,b);L=12288;return 1},Ia:function(a){if(62E3!=a)return L=12296,0;Kb=Jb=Ib=0;Hb=!1;L=12288;return 1},Ea:function(){L=12288;return 1},Da:function(){L=12288;return 1},Na:function(a,b,c){b=ec(b,c);return Ia[a].apply(null,b)},g:function(a,b,c){b=ec(b,c);return Ia[a].apply(null,
b)},Cc:function(a,b,c,d){fc(F(a),function(e){eb(function(){var g=D(e.length);w.set(e,g);G(c)(b,g,e.length);ge(g)})},function(){d&&eb(function(){G(d)(b)})})},$:function(){return Date.now()},pa:function(){if(!sc())return-1;nc(Qc);var a=Hc[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},sa:function(){nc(Rc);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},
l:function(){return devicePixelRatio},j:function(a,b,c){a=W(a);if(!a)return-4;a=Pc(a);A[b>>3]=a.width;A[c>>3]=a.height;return 0},T:function(a,b){if(0>a||a>=uc.length)return-5;if(!uc[a])return-7;Sc(b,uc[a]);return 0},s:Va,Ma:function(){return uc.length},ta:function(a,b){x[a>>2]=screen.width;x[b>>2]=screen.height},Nd:function(a){K.activeTexture(a)},Md:Tc,ka:function(a,b){K.me.beginQueryEXT(a,Q[b])},Kd:function(a,b,c){K.bindAttribLocation(O[a],b,F(c))},Jd:Uc,Id:function(a,b){K.bindFramebuffer(a,Sb[b])},
Hd:function(a,b){K.bindRenderbuffer(a,Tb[b])},Gd:function(a,b){K.bindTexture(a,Ub[b])},Vd:function(a){K.bindVertexArray(Vb[a])},Fd:function(a,b,c,d){K.blendColor(a,b,c,d)},Ed:Vc,Dd:function(a,b){K.blendEquationSeparate(a,b)},Cd:Wc,Bd:function(a,b,c,d){K.blendFuncSeparate(a,b,c,d)},Ad:Xc,zd:function(a,b,c,d){K.bufferSubData(a,b,w.subarray(d,d+c))},yd:function(a){return K.checkFramebufferStatus(a)},xd:Yc,wd:Zc,vd:function(a){K.clearDepth(a)},ud:function(a){K.clearStencil(a)},td:function(a,b,c,d){K.colorMask(!!a,
!!b,!!c,!!d)},sd:$c,rd:function(a,b,c,d,e,g,f,m){K.compressedTexImage2D(a,b,c,d,e,g,m?w.subarray(m,m+f):null)},qd:function(a,b,c,d,e,g,f,m,n){K.compressedTexSubImage2D(a,b,c,d,e,g,f,n?w.subarray(n,n+m):null)},pd:function(a,b,c,d,e,g,f,m){K.copyTexImage2D(a,b,c,d,e,g,f,m)},od:function(a,b,c,d,e,g,f,m){K.copyTexSubImage2D(a,b,c,d,e,g,f,m)},nd:ad,md:bd,ld:function(a){K.cullFace(a)},kd:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Rb[d];e&&(K.deleteBuffer(e),e.name=0,Rb[d]=null)}},jd:function(a,
b){for(var c=0;c<a;++c){var d=x[b+4*c>>2],e=Sb[d];e&&(K.deleteFramebuffer(e),e.name=0,Sb[d]=null)}},id:cd,ma:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Q[d];e&&(K.me.deleteQueryEXT(e),Q[d]=null)}},hd:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Tb[d];e&&(K.deleteRenderbuffer(e),e.name=0,Tb[d]=null)}},fd:function(a){if(a){var b=P[a];b?(K.deleteShader(b),P[a]=null):R(1281)}},ed:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Ub[d];e&&(K.deleteTexture(e),e.name=0,Ub[d]=null)}},
Ud:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];K.deleteVertexArray(Vb[d]);Vb[d]=null}},dd:function(a){K.depthFunc(a)},cd:function(a){K.depthMask(!!a)},bd:function(a,b){K.depthRange(a,b)},ad:function(a,b){K.detachShader(O[a],P[b])},$c:dd,_c:ed,Zc:function(a,b,c){K.drawArrays(a,b,c)},Qd:function(a,b,c,d){K.drawArraysInstanced(a,b,c,d)},Rd:function(a,b){for(var c=fd[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];K.drawBuffers(c)},Yc:gd,Pd:function(a,b,c,d,e){K.drawElementsInstanced(a,b,c,d,e)},Xc:hd,Wc:jd,
ja:function(a){K.me.endQueryEXT(a)},Vc:function(){K.finish()},Uc:function(){K.flush()},Tc:function(a,b,c,d){K.framebufferRenderbuffer(a,b,c,Tb[d])},Sc:function(a,b,c,d,e){K.framebufferTexture2D(a,b,c,Ub[d],e)},Rc:function(a){K.frontFace(a)},Qc:ld,Oc:function(a,b){kd(a,b,"createFramebuffer",Sb)},oa:function(a,b){for(var c=0;c<a;c++){var d=K.me.createQueryEXT();if(!d){for(R(1282);c<a;)x[b+4*c++>>2]=0;break}var e=Zb(Q);d.name=e;Q[e]=d;x[b+4*c>>2]=e}},Mc:function(a,b){kd(a,b,"createRenderbuffer",Tb)},
Lc:function(a,b){kd(a,b,"createTexture",Ub)},Td:function(a,b){kd(a,b,"createVertexArray",Vb)},Pc:function(a){K.generateMipmap(a)},Kc:function(a,b,c,d,e,g,f){md("getActiveAttrib",a,b,c,d,e,g,f)},Jc:function(a,b,c,d,e,g,f){md("getActiveUniform",a,b,c,d,e,g,f)},Ic:function(a,b,c,d){a=K.getAttachedShaders(O[a]);var e=a.length;e>b&&(e=b);x[c>>2]=e;for(b=0;b<e;++b)x[d+4*b>>2]=P.indexOf(a[b])},Hc:nd,Gc:function(a,b){pd(a,b,4)},Fc:function(a,b,c){c?x[c>>2]=K.getBufferParameter(a,b):R(1281)},Ec:function(){var a=
K.getError()||Yb;Yb=0;return a},Dc:function(a,b){pd(a,b,2)},Bc:function(a,b,c,d){a=K.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;x[d>>2]=a},Ac:function(a,b){pd(a,b,0)},yc:qd,zc:rd,ea:sd,ga:td,da:sd,fa:td,ha:function(a,b,c){c?x[c>>2]=K.me.getQueryEXT(a,b):R(1281)},xc:function(a,b,c){c?x[c>>2]=K.getRenderbufferParameter(a,b):R(1281)},vc:function(a,b,c,d){a=K.getShaderInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,d,b):
0;c&&(x[c>>2]=b)},uc:function(a,b,c,d){a=K.getShaderPrecisionFormat(a,b);x[c>>2]=a.rangeMin;x[c+4>>2]=a.rangeMax;x[d>>2]=a.precision},tc:function(a,b,c,d){if(a=K.getShaderSource(P[a]))b=0<b&&d?E(a,d,b):0,c&&(x[c>>2]=b)},wc:function(a,b,c){c?35716==b?(a=K.getShaderInfoLog(P[a]),null===a&&(a="(unknown error)"),x[c>>2]=a?a.length+1:0):35720==b?(a=K.getShaderSource(P[a]),x[c>>2]=a?a.length+1:0):x[c>>2]=K.getShaderParameter(P[a],b):R(1281)},sc:function(a){var b=Wb[a];if(!b){switch(a){case 7939:b=K.getSupportedExtensions()||
[];b=b.concat(b.map(function(d){return"GL_"+d}));b=S(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=K.getParameter(a))||R(1280);b=b&&S(b);break;case 7938:b=S("OpenGL ES 2.0 ("+K.getParameter(7938)+")");break;case 35724:b=K.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=S(b);break;default:R(1280)}Wb[a]=b}return b},qc:function(a,b,c){c?z[c>>2]=K.getTexParameter(a,b):R(1281)},
pc:function(a,b,c){c?x[c>>2]=K.getTexParameter(a,b):R(1281)},mc:wd,oc:function(a,b,c){xd(a,b,c,2)},nc:function(a,b,c){xd(a,b,c,0)},jc:function(a,b,c){c?x[c>>2]=K.getVertexAttribOffset(a,b):R(1281)},lc:function(a,b,c){yd(a,b,c,2)},kc:function(a,b,c){yd(a,b,c,5)},ic:function(a,b){K.hint(a,b)},hc:function(a){return(a=Rb[a])?K.isBuffer(a):0},gc:function(a){return K.isEnabled(a)},fc:function(a){return(a=Sb[a])?K.isFramebuffer(a):0},ec:function(a){return(a=O[a])?K.isProgram(a):0},la:function(a){return(a=
Q[a])?K.me.isQueryEXT(a):0},dc:function(a){return(a=Tb[a])?K.isRenderbuffer(a):0},cc:function(a){return(a=P[a])?K.isShader(a):0},bc:function(a){return(a=Ub[a])?K.isTexture(a):0},Sd:function(a){return(a=Vb[a])?K.isVertexArray(a):0},ac:function(a){K.lineWidth(a)},$b:zd,_b:function(a,b){3317==a&&(Xb=b);K.pixelStorei(a,b)},Zb:function(a,b){K.polygonOffset(a,b)},ia:function(a,b){K.me.queryCounterEXT(Q[a],b)},Yb:function(a,b,c,d,e,g,f){(f=Ad(g,e,c,d,f))?K.readPixels(a,b,c,d,e,g,f):R(1280)},Xb:function(){},
Wb:function(a,b,c,d){K.renderbufferStorage(a,b,c,d)},Vb:function(a,b){K.sampleCoverage(a,!!b)},Ub:function(a,b,c,d){K.scissor(a,b,c,d)},Tb:function(){R(1280)},Sb:Bd,Rb:function(a,b,c){K.stencilFunc(a,b,c)},Qb:function(a,b,c,d){K.stencilFuncSeparate(a,b,c,d)},Pb:function(a){K.stencilMask(a)},Nb:function(a,b){K.stencilMaskSeparate(a,b)},Mb:function(a,b,c){K.stencilOp(a,b,c)},Lb:function(a,b,c,d){K.stencilOpSeparate(a,b,c,d)},Kb:function(a,b,c,d,e,g,f,m,n){K.texImage2D(a,b,c,d,e,g,f,m,n?Ad(m,f,d,e,n):
null)},Jb:function(a,b,c){K.texParameterf(a,b,c)},Ib:function(a,b,c){K.texParameterf(a,b,z[c>>2])},Hb:function(a,b,c){K.texParameteri(a,b,c)},Gb:function(a,b,c){K.texParameteri(a,b,x[c>>2])},Fb:function(a,b,c,d,e,g,f,m,n){var r=null;n&&(r=Ad(m,f,e,g,n));K.texSubImage2D(a,b,c,d,e,g,f,m,r)},Eb:Cd,Db:function(a,b,c){if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);K.uniform1fv(X(a),d)},Cb:function(a,b){K.uniform1i(X(a),b)},Bb:function(a,b,c){if(288>=b)for(var d=
Dd[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);K.uniform1iv(X(a),d)},Ab:function(a,b,c){K.uniform2f(X(a),b,c)},zb:function(a,b,c){if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);K.uniform2fv(X(a),d)},yb:function(a,b,c){K.uniform2i(X(a),b,c)},xb:function(a,b,c){if(144>=b)for(var d=Dd[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);K.uniform2iv(X(a),d)},wb:Ed,vb:function(a,
b,c){if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);K.uniform3fv(X(a),d)},ub:function(a,b,c,d){K.uniform3i(X(a),b,c,d)},tb:function(a,b,c){if(96>=b)for(var d=Dd[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);K.uniform3iv(X(a),d)},sb:function(a,b,c,d,e){K.uniform4f(X(a),b,c,d,e)},rb:function(a,b,c){if(72>=b){var d=Y[4*b-1],e=z;c>>=2;for(var g=
0;g<4*b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=z.subarray(c>>2,c+16*b>>2);K.uniform4fv(X(a),d)},qb:function(a,b,c,d,e){K.uniform4i(X(a),b,c,d,e)},pb:function(a,b,c){if(72>=b)for(var d=Dd[4*b-1],e=0;e<4*b;e+=4)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2],d[e+3]=x[c+(4*e+12)>>2];else d=x.subarray(c>>2,c+16*b>>2);K.uniform4iv(X(a),d)},ob:function(a,b,c,d){if(72>=b)for(var e=Y[4*b-1],g=0;g<4*b;g+=4)e[g]=z[d+4*g>>2],e[g+1]=z[d+(4*g+4)>>2],e[g+2]=z[d+
(4*g+8)>>2],e[g+3]=z[d+(4*g+12)>>2];else e=z.subarray(d>>2,d+16*b>>2);K.uniformMatrix2fv(X(a),!!c,e)},nb:function(a,b,c,d){if(32>=b)for(var e=Y[9*b-1],g=0;g<9*b;g+=9)e[g]=z[d+4*g>>2],e[g+1]=z[d+(4*g+4)>>2],e[g+2]=z[d+(4*g+8)>>2],e[g+3]=z[d+(4*g+12)>>2],e[g+4]=z[d+(4*g+16)>>2],e[g+5]=z[d+(4*g+20)>>2],e[g+6]=z[d+(4*g+24)>>2],e[g+7]=z[d+(4*g+28)>>2],e[g+8]=z[d+(4*g+32)>>2];else e=z.subarray(d>>2,d+36*b>>2);K.uniformMatrix3fv(X(a),!!c,e)},mb:Fd,lb:Gd,kb:function(a){K.validateProgram(O[a])},jb:function(a,
b){K.vertexAttrib1f(a,b)},ib:function(a,b){K.vertexAttrib1f(a,z[b>>2])},hb:function(a,b,c){K.vertexAttrib2f(a,b,c)},gb:function(a,b){K.vertexAttrib2f(a,z[b>>2],z[b+4>>2])},fb:function(a,b,c,d){K.vertexAttrib3f(a,b,c,d)},eb:function(a,b){K.vertexAttrib3f(a,z[b>>2],z[b+4>>2],z[b+8>>2])},db:function(a,b,c,d,e){K.vertexAttrib4f(a,b,c,d,e)},cb:function(a,b){K.vertexAttrib4f(a,z[b>>2],z[b+4>>2],z[b+8>>2],z[b+12>>2])},Od:function(a,b){K.vertexAttribDivisor(a,b)},bb:Hd,ab:Id,q:function(){return 0},$a:function(a,
b,c){w.copyWithin(a,b,b+c)},qa:function(a,b,c){return Jd(a,{Ce:x[c>>2],Ae:x[c+4>>2],Xe:x[c+8>>2],Ue:b,te:x[c+12>>2],Ge:x[c+16>>2]})},O:function(a,b){a=W(a);return a?a.requestPointerLock?jc&&pc.pe?Rc(a):b?(mc(Rc,2,[a]),1):-2:-1:-4},Ua:function(){p("OOM")},m:function(a){eval(F(a))},U:function(){return(uc=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},t:function(a,b,c){if("undefined"==typeof onbeforeunload)return-1;if(1!==c)return-5;
Kd(a,b);return 0},F:function(a,b,c,d){Ld(a,b,c,d,12,"blur");return 0},k:Lc,o:function(a,b,c){a=W(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},G:function(a,b,c,d){Ld(a,b,c,d,13,"focus");return 0},v:function(a,b,c,d){if(!sc())return-1;a=W(a);if(!a)return-4;Md(a,b,c,d,"fullscreenchange");Md(a,b,c,d,"webkitfullscreenchange");return 0},S:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;Nd(a,b,c,26,"gamepadconnected");return 0},R:function(a,b,c){if(!navigator.getGamepads&&
!navigator.webkitGetGamepads)return-1;Nd(a,b,c,27,"gamepaddisconnected");return 0},y:function(a,b,c,d){Od(a,b,c,d,2,"keydown");return 0},w:function(a,b,c,d){Od(a,b,c,d,1,"keypress");return 0},x:function(a,b,c,d){Od(a,b,c,d,3,"keyup");return 0},Oa:function(a,b,c){a=G(a);Ya(a,b,c)},M:function(a,b,c,d){Qd(a,b,c,d,5,"mousedown");return 0},J:function(a,b,c,d){Qd(a,b,c,d,33,"mouseenter");return 0},I:function(a,b,c,d){Qd(a,b,c,d,34,"mouseleave");return 0},N:function(a,b,c,d){Qd(a,b,c,d,8,"mousemove");return 0},
L:function(a,b,c,d){Qd(a,b,c,d,6,"mouseup");return 0},A:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.ue||document.body.$e||document.body.Ye))return-1;a=W(a);if(!a)return-4;Rd(a,b,c,d,"pointerlockchange");Rd(a,b,c,d,"mozpointerlockchange");Rd(a,b,c,d,"webkitpointerlockchange");Rd(a,b,c,d,"mspointerlockchange");return 0},r:function(a,b,c,d){Sd(a,b,c,d);return 0},B:function(a,b,c,d){Td(a,b,c,d,25,"touchcancel");return 0},D:function(a,b,c,d){Td(a,b,
c,d,23,"touchend");return 0},C:function(a,b,c,d){Td(a,b,c,d,24,"touchmove");return 0},E:function(a,b,c,d){Td(a,b,c,d,22,"touchstart");return 0},u:function(a,b,c){Ud(a,b,c);return 0},H:function(a,b,c,d){a=W(a);return"undefined"!=typeof a.onwheel?(Vd(a,b,c,d),0):-1},ra:function(a){fa(F(a))},p:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Va:function(a,b){var c=0;Xd().forEach(function(d,e){var g=b+c;e=y[a+4*e>>2]=g;for(g=
0;g<d.length;++g)u[e++>>0]=d.charCodeAt(g);u[e>>0]=0;c+=d.length+1});return 0},Wa:function(a,b){var c=Xd();y[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});y[b>>2]=d;return 0},Y:function(){return 52},Xa:function(){return 52},Ta:function(){return 70},Z:function(a,b,c,d){for(var e=0,g=0;g<c;g++){var f=y[b>>2],m=y[b+4>>2];b+=8;for(var n=0;n<m;n++){var r=w[f+n],t=de[a];0===r||10===r?((1===a?ha:l)(Oa(t,0)),t.length=0):t.push(r)}e+=m}y[d>>2]=e;return 0},ca:Tc,a:Uc,Qa:Vc,Ra:Wc,b:Xc,Ob:Yc,Pa:Zc,
z:$c,na:ad,P:bd,Ga:cd,W:dd,Sa:ed,i:gd,X:hd,e:jd,c:ld,ba:nd,La:qd,V:rd,n:wd,Ld:zd,K:Bd,aa:Cd,d:Ed,h:Fd,gd:Gd,f:Hd,rc:Id,Nc:function(){return"https:"===location.protocol}};
(function(){function a(c){c=c.exports;h.asm=c;ja=h.asm.Wd;var d=ja.buffer;h.HEAP8=u=new Int8Array(d);h.HEAP16=la=new Int16Array(d);h.HEAP32=x=new Int32Array(d);h.HEAPU8=w=new Uint8Array(d);h.HEAPU16=ma=new Uint16Array(d);h.HEAPU32=y=new Uint32Array(d);h.HEAPF32=z=new Float32Array(d);h.HEAPF64=A=new Float64Array(d);na=h.asm.$d;qa.unshift(h.asm.Xd);B--;h.monitorRunDependencies&&h.monitorRunDependencies(B);0==B&&(null!==va&&(clearInterval(va),va=null),wa&&(d=wa,wa=null,d()));return c}var b={a:he};B++;
h.monitorRunDependencies&&h.monitorRunDependencies(B);if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return l("Module.instantiateWasm callback failed with error: "+c),!1}Ca(b,function(c){a(c.instance)});return{}})();function D(){return(D=h.asm.Yd).apply(null,arguments)}function ge(){return(ge=h.asm.Zd).apply(null,arguments)}var ie=h._main=function(){return(ie=h._main=h.asm._d).apply(null,arguments)};function hc(){return(hc=h.asm.ae).apply(null,arguments)}
function ic(){return(ic=h.asm.be).apply(null,arguments)}function Jc(){return(Jc=h.asm.ce).apply(null,arguments)}h.dynCall_jiji=function(){return(h.dynCall_jiji=h.asm.de).apply(null,arguments)};h.dynCall_ji=function(){return(h.dynCall_ji=h.asm.ee).apply(null,arguments)};h.___start_em_js=87552;h.___stop_em_js=87601;var je;wa=function ke(){je||le();je||(wa=ke)};
function me(a=[]){var b=ie;a.unshift(ca);var c=a.length,d=Jc(4*(c+1)),e=d>>2;a.forEach(f=>{x[e++]=Ic(f)});x[e]=0;try{var g=b(c,d);gb(g)}catch(f){fb(f)}}
function le(){var a=ba;function b(){if(!je&&(je=!0,h.calledRun=!0,!q)){La(qa);La(ra);if(h.onRuntimeInitialized)h.onRuntimeInitialized();ne&&me(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();ta.unshift(c)}La(ta)}}if(!(0<B)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)ua();La(oa);0<B||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},
1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var ne=!0;h.noInitialRun&&(ne=!1);le();
