var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},h),ba=[],ca="./this.program",da=(a,b)=>{throw b;},k="",ea;"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src);k=0!==k.indexOf("blob:")?k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1):"";ea=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};
var fa=h.print||console.log.bind(console),l=h.printErr||console.error.bind(console);Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);h.quit&&(da=h.quit);var ha;h.wasmBinary&&(ha=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!=typeof WebAssembly&&p("no native wasm support detected");var ia,q=!1,ja,t,u,ka,la,w,x,y,A,ma=[],na=[],oa=[],pa=[],qa=[];function ra(){var a=h.preRun.shift();ma.unshift(a)}var B=0,sa=null,ta=null;
function p(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";l(a);q=!0;ja=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function ua(a){return a.startsWith("data:application/octet-stream;base64,")}var C;C="index.wasm";if(!ua(C)){var va=C;C=h.locateFile?h.locateFile(va,k):k+va}function wa(a){if(a==C&&ha)return new Uint8Array(ha);throw"both async and sync fetching of the wasm failed";}
function xa(a){return ha||"function"!=typeof fetch?Promise.resolve().then(()=>wa(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>wa(a))}function ya(a,b,c){return xa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{l(`failed to asynchronously prepare wasm: ${d}`);p(d)})}
function za(a,b){var c=C;ha||"function"!=typeof WebAssembly.instantiateStreaming||ua(c)||"function"!=typeof fetch?ya(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){l(`wasm streaming compile failed: ${e}`);l("falling back to ArrayBuffer instantiation");return ya(c,a,b)}))}
var Da={87633:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,87780:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,88014:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.de||("undefined"!==typeof AudioContext?b.de=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.de=new webkitAudioContext),b.de&&Aa(b.de));
return void 0===b.de?-1:0},88507:()=>h.SDL2.de.sampleRate,88575:(a,b,c,d)=>{function e(){}function f(m){void 0!==g.capture.pe&&(clearTimeout(g.capture.pe),g.capture.pe=void 0);g.capture.we=g.de.createMediaStreamSource(m);g.capture.fe=g.de.createScriptProcessor(b,a,1);g.capture.fe.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.ze=n.inputBuffer,Ba(c,[d]))};g.capture.we.connect(g.capture.fe);g.capture.fe.connect(g.de.destination);g.capture.stream=
m}var g=h.SDL2;g.capture.xe=g.de.createBuffer(a,b,g.de.sampleRate);g.capture.xe.getChannelData(0).fill(0);g.capture.pe=setTimeout(function(){g.capture.ze=g.capture.xe;Ba(c,[d])},b/g.de.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},90227:(a,b,c,d)=>{var e=h.SDL2;e.audio.fe=e.de.createScriptProcessor(b,
0,a);e.audio.fe.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Fe=f.outputBuffer,Ba(c,[d]))};e.audio.fe.connect(e.de.destination)},90637:(a,b)=>{for(var c=h.SDL2,d=c.capture.ze.numberOfChannels,e=0;e<d;++e){var f=c.capture.ze.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Ca(a+4*g,f[g]);else for(g=0;g<b;++g)Ca(a+4*(g*d+e),f[g])}},91242:(a,b)=>{for(var c=
h.SDL2,d=c.audio.Fe.numberOfChannels,e=0;e<d;++e){var f=c.audio.Fe.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=y[a+(g*d+e<<2)>>2]}},91722:a=>{var b=h.SDL2;if(a){void 0!==b.capture.pe&&clearTimeout(b.capture.pe);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==b.capture.fe&&
(b.capture.fe.onaudioprocess=function(){},b.capture.fe.disconnect(),b.capture.fe=void 0);void 0!==b.capture.we&&(b.capture.we.disconnect(),b.capture.we=void 0);void 0!==b.capture.xe&&(b.capture.xe=void 0);b.capture=void 0}else void 0!=b.audio.fe&&(b.audio.fe.disconnect(),b.audio.fe=void 0),b.audio=void 0;void 0!==b.de&&void 0===b.audio&&void 0===b.capture&&(b.de.close(),b.de=void 0)},92894:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Me!==h.canvas&&(d.je=h.createContext(h.canvas,!1,!0),d.Me=h.canvas);
if(d.w!==a||d.h!==b||d.Ye!==d.je)d.image=d.je.createImageData(a,b),d.w=a,d.h=b,d.Ye=d.je;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=w[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Pe!==a&&(d.Oe=new Int32Array(a.buffer),d.Qe=new Uint8Array(a.buffer),d.Pe=a),a=d.Oe,c=a.length,a.set(w.subarray(b,b+c)),a=d.Qe,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|
0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.je.putImageData(d.image,0,0)},94363:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var r=w[e];b[m]=r&255;b[m+1]=r>>8&255;b[m+2]=r>>16&255;b[m+3]=r>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),
n=b.length,b.set(w.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=D(c.length+1);E(c,d,c.length+1);return d},95352:a=>{h.canvas&&(h.canvas.style.cursor=a?F(u,a):"")},95435:()=>{h.canvas&&(h.canvas.style.cursor="none")},95504:()=>window.innerWidth,95534:()=>window.innerHeight};function Ea(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Fa=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Aa=a=>{var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&Fa(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Ga=a=>{for(;0<a.length;)a.shift()(h)},Ha=[],Ia,G=a=>{var b=Ha[a];b||(a>=Ha.length&&(Ha.length=a+1),Ha[a]=b=Ia.get(a));return b},Ba=(a,b)=>{if("vi".includes("j")){var c=h.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else G(a).apply(null,b)};
function Ca(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":t[a>>0]=b;break;case "i8":t[a>>0]=b;break;case "i16":ka[a>>1]=b;break;case "i32":w[a>>2]=b;break;case "i64":p("to do setValue(i64) use WASM_BIGINT");case "float":y[a>>2]=b;break;case "double":A[a>>3]=b;break;case "*":x[a>>2]=b;break;default:p(`invalid type for setValue: ${c}`)}}
var Ja="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,F=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ja)return Ja.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Ua=(a,b)=>{Ka=a;La=b;if(Ma)if(Na||(Na=!0),0==a)H=function(){var d=Math.max(0,Oa+b-Ra())|0;setTimeout(Sa,d)};else if(1==a)H=function(){Ta(Sa)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}H=function(){setImmediate(Sa)}}},Ra;Ra=()=>performance.now();
var ab=(a,b,c,d,e)=>{!Ma||p("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Ma=a;Va=d;var f=I;Na=!1;Sa=function(){if(!q)if(0<Wa.length){var g=Wa.shift();g.hf(g.df);if(Xa){var m=Xa,n=0==m%1?m-1:Math.floor(m);Xa=g.ff?n:(8*m+(n+.5))/9}h.setStatus&&(g=h.statusMessage||"Please wait...",m=Xa,n=Ya.gf,m?m<n?h.setStatus(g+" ("+(n-m)+"/"+n+")"):h.setStatus(g):h.setStatus(""));
f<I||setTimeout(Sa,0)}else f<I||(Za=Za+1|0,1==Ka&&1<La&&0!=Za%La?H():(0==Ka&&(Oa=Ra()),q||h.preMainLoop&&!1===h.preMainLoop()||($a(a),h.postMainLoop&&h.postMainLoop()),f<I||("object"==typeof SDL&&SDL.audio&&SDL.audio.$e&&SDL.audio.$e(),H())))};e||(b&&0<b?Ua(0,1E3/b):Ua(1,1),H());if(c)throw"unwind";},bb=a=>{a instanceof Ea||"unwind"==a||da(1,a)},cb=a=>{ja=a;if(!noExitRuntime){if(h.onExit)h.onExit(a);q=!0}da(a,new Ea(a))},db=a=>{ja=a;cb(a)},$a=a=>{if(!q)try{if(a(),!noExitRuntime)try{ja=a=ja,cb(a)}catch(b){bb(b)}}catch(b){bb(b)}},
Na=!1,H=null,I=0,Ma=null,Va=0,Ka=0,La=0,Za=0,Wa=[],Ya={},Oa,Sa,Xa,eb=!1,fb=!1,gb=[];
function hb(){function a(){fb=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!ib){ib=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!fb&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function jb(a,b,c,d){if(b&&h.je&&a==h.canvas)return h.je;var e;if(b){var f={antialias:!1,alpha:!1,He:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof kb&&(e=lb(a,f)))var m=J[e].le}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof K||p("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.je=m,b&&mb(e),h.bf=b,gb.forEach(n=>n()),hb());return m}var nb=!1,ob=void 0,pb=void 0;
function qb(a,b){function c(){eb=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=rb,ob&&d.requestPointerLock(),eb=!0,pb?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>2]|8388608),sb(h.canvas),tb()):sb(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),pb?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>2]&
-8388609),sb(h.canvas),tb()):sb(d));if(h.onFullScreen)h.onFullScreen(eb);if(h.onFullscreen)h.onFullscreen(eb)}ob=a;pb=b;"undefined"==typeof ob&&(ob=!0);"undefined"==typeof pb&&(pb=!1);var d=h.canvas;nb||(nb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function rb(){if(!eb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var ub=0;function Ta(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ub)ub=b+1E3/60;else for(;b+2>=ub;)ub+=1E3/60;setTimeout(a,Math.max(ub-b,0))}}var vb=[];function tb(){var a=h.canvas;vb.forEach(b=>b(a.width,a.height))}
function sb(a,b,c){b&&c?(a.cf=b,a.Xe=c):(b=a.cf,c=a.Xe);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}pb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var ib,L=12288,wb=!1,xb=0,yb=0,zb=0,M={alpha:!1,depth:!1,stencil:!1,antialias:!1},Ab={},Bb,Cb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Db=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Eb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Fb=1,Gb=[],N=[],Hb=[],Ib=[],Jb=[],O=[],Kb=[],J=[],P=[],Lb={},Mb=4;function Q(a){Nb||(Nb=a)}
var Ob=a=>{for(var b=Fb++,c=a.length;c<b;c++)a[c]=null;return b},lb=(a,b)=>{a.se||(a.se=a.getContext,a.getContext=function(d,e){e=a.se(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Pb(c,b):0},Pb=(a,b)=>{var c=Ob(J),d={handle:c,attributes:b,version:b.He,le:a};a.canvas&&(a.canvas.ne=d);J[c]=d;("undefined"==typeof b.Te||b.Te)&&Qb(d);return c},mb=a=>{Rb=J[a];h.je=K=Rb&&Rb.le},Qb=a=>{a||(a=Rb);if(!a.Ze){a.Ze=!0;var b=a.le;Cb(b);Db(b);Eb(b);b.ke=
b.getExtension("EXT_disjoint_timer_query");b.lf=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},kb={},Nb,Rb,Sb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},E=(a,b,c)=>{var d=u;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+
((g&1023)<<10)|m&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},R=a=>{var b=Sb(a)+1,c=D(b);c&&E(a,c,b);return c},Tb=[],Ub=(a,b)=>{Tb.length=0;for(var c;c=u[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Tb.push(112==c?x[b>>2]:105==c?w[b>>2]:A[b>>3]);b+=d?8:4}return Tb},Vb=(a,b,c)=>{ea(a,d=>{d||p(`Loading data file "${a}" failed (no arrayBuffer).`);
b(new Uint8Array(d))},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;})},Yb=a=>{var b=Wb();a=a();Xb(b);return a},Zb=0;function $b(){for(var a=S.length-1;0<=a;--a)ac(a);S=[];T=[]}var T=[];function bc(a,b,c){function d(g,m){if(g.length!=m.length)return!1;for(var n in g)if(g[n]!=m[n])return!1;return!0}for(var e in T){var f=T[e];if(f.Be==a&&d(f.De,c))return}T.push({Be:a,Je:b,De:c});T.sort((g,m)=>g.Je<m.Je)}function cc(a){for(var b=0;b<T.length;++b)T[b].Be==a&&(T.splice(b,1),--b)}
function dc(){return navigator.userActivation?navigator.userActivation.isActive:Zb&&ec.oe}function fc(){if(dc())for(var a=0;a<T.length;++a){var b=T[a];T.splice(a,1);--a;b.Be.apply(null,b.De)}}var S=[];function ac(a){var b=S[a];b.target.removeEventListener(b.ee,b.Ue,b.ge);S.splice(a,1)}
function U(a){function b(d){++Zb;ec=a;fc();a.ie(d);fc();--Zb}if(!a.target)return-4;if(a.he)a.Ue=b,a.target.addEventListener(a.ee,b,a.ge),S.push(a),gc||(pa.push($b),gc=!0);else for(var c=0;c<S.length;++c)S[c].target==a.target&&S[c].ee==a.ee&&ac(c--);return 0}function hc(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function ic(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var jc={},gc,ec,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc={},xc=[0,document,window],V=a=>{a=2<a?a?F(u,a):"":a;return xc[a]||document.querySelector(a)},zc=a=>{var b=Sb(a)+1,c=yc(b);E(a,c,b);return c},Ac=a=>Yb(()=>{var b=yc(8),c=b+4,d=zc(a.id);if(d=V(d))w[b>>2]=d.width,w[c>>2]=d.height;return[w[b>>2],w[c>>2]]}),Bc=(a,b,c)=>{a=V(a);if(!a)return-4;a.width=b;a.height=c;return 0},Cc=(a,b,c)=>{a.ef?Yb(()=>{var d=zc(a.id);Bc(d,b,c)}):(a.width=b,a.height=c)},Dc=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||
(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Cc(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=r,a.style.paddingRight=v,a.style.paddingTop=z,a.style.paddingBottom=Pa,a.style.marginLeft=Qa,a.style.marginRight=Md,a.style.marginTop=Nd,a.style.marginBottom=Od,document.body.style.margin=Pd,document.documentElement.style.overflow=
Qd,document.body.scroll=Rd,a.style.me=Sd,a.ne&&a.ne.le.viewport(0,0,d,e),wc.re&&G(wc.re)(37,0,wc.Ee))}var c=Ac(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,r=a.style.paddingLeft,v=a.style.paddingRight,z=a.style.paddingTop,Pa=a.style.paddingBottom,Qa=a.style.marginLeft,Md=a.style.marginRight,Nd=a.style.marginTop,Od=a.style.marginBottom,Pd=document.body.style.margin,Qd=document.documentElement.style.overflow,Rd=document.body.scroll,
Sd=a.style.me;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},Ec=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Fc=a=>0>xc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Gc=(a,b)=>{if(0!=b.Ae||0!=b.ye){Dc(a);var c=b.af?innerWidth:screen.width,d=b.af?innerHeight:screen.height,e=Fc(a),f=e.width;e=e.height;var g=Ac(a),m=g[0];g=g[1];3==b.Ae?(Ec(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Ae&&(c*
g<m*d?(f=g*c/m,Ec(a,(d-f)/2,0),d=f):(f=m*d/g,Ec(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.We&&(a.style.me="optimizeSpeed",a.style.me="-moz-crisp-edges",a.style.me="-o-crisp-edges",a.style.me="-webkit-optimize-contrast",a.style.me="optimize-contrast",a.style.me="crisp-edges",a.style.me="pixelated");f=2==b.ye?devicePixelRatio:1;0!=b.ye&&
(c=c*f|0,d=d*f|0,Cc(a,c,d),a.ne&&a.ne.le.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return ic()?-3:-1;wc=b;b.re&&G(b.re)(37,0,b.Ee);return 0},Hc=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Ic=(a,b)=>{A[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)A[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)A[a+8*c+528>>
3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)w[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];w[a+1296>>2]=b.connected;w[a+1300>>2]=b.index;w[a+8>>2]=b.axes.length;w[a+12>>2]=b.buttons.length;E(b.id,a+1304,64);E(b.mapping,a+1368,64)},Jc=(a,b)=>{K.attachShader(N[a],O[b])},Kc=(a,b)=>{K.bindBuffer(a,Gb[b])};function Lc(a){K.blendEquation(a)}function Mc(a,b){K.blendFunc(a,b)}
var Nc=(a,b,c,d)=>{K.bufferData(a,c?u.subarray(c,c+b):b,d)};function Oc(a){K.clear(a)}function Pc(a,b,c,d){K.clearColor(a,b,c,d)}var Qc=a=>{K.compileShader(O[a])},Rc=()=>{var a=Ob(N),b=K.createProgram();b.name=a;b.ve=b.te=b.ue=0;b.Ce=1;N[a]=b;return a},Sc=a=>{var b=Ob(O);O[b]=K.createShader(a);return b},Tc=a=>{if(a){var b=N[a];b?(K.deleteProgram(b),b.name=0,N[a]=null):Q(1281)}};function Uc(a){K.disable(a)}var Vc=[],Wc=(a,b,c,d)=>{K.drawElements(a,b,c,d)};function Xc(a){K.enable(a)}
var Yc=a=>{K.enableVertexAttribArray(a)},Zc=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=K[c](),g=f&&Ob(d);f?(f.name=g,d[g]=f):Q(1282);w[b+4*e>>2]=g}},$c=(a,b)=>{Zc(a,b,"createBuffer",Gb)},ad=(a,b,c,d,e,f,g,m)=>{b=N[b];if(a=K[a](b,c))d=m&&E(a.name,m,d),e&&(w[e>>2]=d),f&&(w[f>>2]=a.size),g&&(w[g>>2]=a.type)},bd=(a,b)=>K.getAttribLocation(N[a],b?F(u,b):""),cd=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&Q(1280);return;case 36345:d=0;break;case 34466:var e=K.getParameter(34467);
d=e?e.length:0}if(void 0===d)switch(e=K.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":Q(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:Q(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:w[b+4*a>>2]=e[a];break;case 2:y[b+4*a>>2]=e[a];break;
case 4:t[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){Q(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:Q(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:c=d;x[b>>2]=c;x[b+4>>2]=(c-x[b>>2])/4294967296;break;case 0:w[b>>2]=d;break;case 2:y[b>>2]=d;break;case 4:t[b>>0]=d?1:0}}else Q(1281)},dd=(a,b,c,d)=>{a=K.getProgramInfoLog(N[a]);
null===a&&(a="(unknown error)");b=0<b&&d?E(a,d,b):0;c&&(w[c>>2]=b)},ed=(a,b,c)=>{if(c)if(a>=Fb)Q(1281);else if(a=N[a],35716==b)a=K.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b){if(!a.ve)for(b=0;b<K.getProgramParameter(a,35718);++b)a.ve=Math.max(a.ve,K.getActiveUniform(a,b).name.length+1);w[c>>2]=a.ve}else if(35722==b){if(!a.te)for(b=0;b<K.getProgramParameter(a,35721);++b)a.te=Math.max(a.te,K.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.te}else if(35381==
b){if(!a.ue)for(b=0;b<K.getProgramParameter(a,35382);++b)a.ue=Math.max(a.ue,K.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.ue}else w[c>>2]=K.getProgramParameter(a,b);else Q(1281)},fd=(a,b,c)=>{if(c){a=K.ke.getQueryObjectEXT(P[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d;x[c+4>>2]=(d-x[c>>2])/4294967296}else Q(1281)},gd=(a,b,c)=>{if(c){a=K.ke.getQueryObjectEXT(P[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d}else Q(1281)},hd=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),jd=a=>{var b=
a.qe,c=a.Le,d;if(!b)for(a.qe=b={},a.Ke={},d=0;d<K.getProgramParameter(a,35718);++d){var e=K.getActiveUniform(a,d);var f=e.name;e=e.size;var g=hd(f);g=0<g?f.slice(0,g):f;var m=a.Ce;a.Ce+=e;c[g]=[e,m];for(f=0;f<e;++f)b[m]=f,a.Ke[m++]=g}},kd=(a,b)=>{b=b?F(u,b):"";if(a=N[a]){jd(a);var c=a.qe,d=0,e=b,f=hd(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Le[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||K.getUniformLocation(a,b)))return d}else Q(1281);return-1},W=a=>{var b=K.Ne;if(b){var c=b.qe[a];"number"==
typeof c&&(b.qe[a]=c=K.getUniformLocation(b,b.Ke[a]+(0<c?"["+c+"]":"")));return c}Q(1282)},ld=(a,b,c,d)=>{if(c)if(a=N[a],jd(a),a=K.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:y[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b]}else Q(1281)},md=(a,b,c,d)=>{if(c)if(a=K.getVertexAttrib(a,b),34975==b)w[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;
case 2:y[c>>2]=a;break;case 5:w[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b];break;case 5:w[c+4*b>>2]=Math.fround(a[b])}else Q(1281)},nd=a=>{a=N[a];K.linkProgram(a);a.qe=0;a.Le={}},od=(a,b,c,d,e)=>{a-=5120;a=1==a?u:4==a?w:6==a?y:5==a||28922==a?x:la;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=Mb;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)},pd=(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=
d?w[d+4*f>>2]:-1,m=w[c+4*f>>2];g=m?F(u,m,0>g?void 0:g):"";e+=g}K.shaderSource(O[a],e)},qd=(a,b)=>{K.uniform1f(W(a),b)},X=[],rd=[],sd=(a,b,c,d)=>{K.uniform3f(W(a),b,c,d)},td=(a,b,c,d)=>{if(18>=b){var e=X[16*b-1],f=y;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=y.subarray(d>>
2,d+64*b>>2);K.uniformMatrix4fv(W(a),!!c,e)},ud=a=>{a=N[a];K.useProgram(a);K.Ne=a},vd=(a,b,c,d,e,f)=>{K.vertexAttribPointer(a,b,c,!!d,e,f)};function wd(a,b,c,d){K.viewport(a,b,c,d)}
var xd=(a,b)=>{if(!ic())return-1;a=V(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?dc()?Gc(a,b):b.Re?(bc(Gc,1,[a,b]),1):-2:-3:-4},yd=(a,b)=>{var c={target:V(2),ee:"beforeunload",he:b,ie:(d=event)=>{var e=G(b)(28,0,a);e&&(e=e?F(u,e):"");if(e)return d.preventDefault(),d.returnValue=e},ge:!0};return U(c)},zd=(a,b,c,d,e,f)=>{lc||(lc=D(256));a={target:V(a),ee:f,he:d,ie:(g=event)=>{var m=g.target.id?g.target.id:"",n=lc;E(hc(g.target),n+0,128);E(m,n+128,128);G(d)(e,n,b)&&g.preventDefault()},
ge:c};return U(a)},Ad=(a,b,c,d,e)=>{nc||(nc=D(280));return U({target:a,ee:e,he:d,ie:(f=event)=>{var g=nc,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;w[g>>2]=n;w[g+4>>2]=ic();var r=n?m:mc,v=r&&r.id?r.id:"";E(hc(r),g+8,128);E(v,g+136,128);w[g+264>>2]=r?r.clientWidth:0;w[g+268>>2]=r?r.clientHeight:0;w[g+272>>2]=screen.width;w[g+276>>2]=screen.height;n&&(mc=m);G(d)(19,g,b)&&f.preventDefault()},ge:c})},Bd=(a,b,c,d,e)=>
{oc||(oc=D(1432));b={target:V(2),oe:!0,ee:e,he:c,ie:(f=event)=>{var g=oc;Ic(g,f.gamepad);G(c)(d,g,a)&&f.preventDefault()},ge:b};return U(b)},Cd=(a,b,c,d,e,f)=>{pc||(pc=D(176));a={target:V(a),oe:!0,ee:f,he:d,ie:g=>{var m=pc;A[m>>3]=g.timeStamp;var n=m>>2;w[n+2]=g.location;w[n+3]=g.ctrlKey;w[n+4]=g.shiftKey;w[n+5]=g.altKey;w[n+6]=g.metaKey;w[n+7]=g.repeat;w[n+8]=g.charCode;w[n+9]=g.keyCode;w[n+10]=g.which;E(g.key||"",m+44,32);E(g.code||"",m+76,32);E(g.char||"",m+108,32);E(g.locale||"",m+140,32);G(d)(e,
m,b)&&g.preventDefault()},ge:c};return U(a)},Dd=(a,b,c)=>{A[a>>3]=b.timeStamp;a>>=2;w[a+2]=b.screenX;w[a+3]=b.screenY;w[a+4]=b.clientX;w[a+5]=b.clientY;w[a+6]=b.ctrlKey;w[a+7]=b.shiftKey;w[a+8]=b.altKey;w[a+9]=b.metaKey;ka[2*a+20]=b.button;ka[2*a+21]=b.buttons;w[a+11]=b.movementX;w[a+12]=b.movementY;c=Fc(c);w[a+13]=b.clientX-c.left;w[a+14]=b.clientY-c.top},Ed=(a,b,c,d,e,f)=>{qc||(qc=D(72));a=V(a);return U({target:a,oe:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,ee:f,he:d,ie:(g=event)=>{Dd(qc,
g,a);G(d)(e,qc,b)&&g.preventDefault()},ge:c})},Fd=(a,b,c,d,e)=>{rc||(rc=D(260));return U({target:a,ee:e,he:d,ie:(f=event)=>{var g=rc,m=document.pointerLockElement||document.se||document.Ve||document.Se;w[g>>2]=!!m;var n=m&&m.id?m.id:"";E(hc(m),g+4,128);E(n,g+132,128);G(d)(20,g,b)&&f.preventDefault()},ge:c})},Gd=(a,b,c,d)=>{sc||(sc=D(36));a=V(a);return U({target:a,ee:"resize",he:d,ie:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=sc;w[g>>2]=e.detail;w[g+4>>2]=f.clientWidth;w[g+8>>2]=f.clientHeight;
w[g+12>>2]=innerWidth;w[g+16>>2]=innerHeight;w[g+20>>2]=outerWidth;w[g+24>>2]=outerHeight;w[g+28>>2]=pageXOffset;w[g+32>>2]=pageYOffset;G(d)(10,g,b)&&e.preventDefault()}}},ge:c})},Hd=(a,b,c,d,e,f)=>{tc||(tc=D(1696));a=V(a);return U({target:a,oe:"touchstart"==f||"touchend"==f,ee:f,he:d,ie:g=>{for(var m,n={},r=g.touches,v=0;v<r.length;++v)m=r[v],m.Ge=m.Ie=0,n[m.identifier]=m;for(v=0;v<g.changedTouches.length;++v)m=g.changedTouches[v],m.Ge=1,n[m.identifier]=m;for(v=0;v<g.targetTouches.length;++v)n[g.targetTouches[v].identifier].Ie=
1;r=tc;A[r>>3]=g.timeStamp;var z=r>>2;w[z+3]=g.ctrlKey;w[z+4]=g.shiftKey;w[z+5]=g.altKey;w[z+6]=g.metaKey;z+=7;var Pa=Fc(a),Qa=0;for(v in n)if(m=n[v],w[z]=m.identifier,w[z+1]=m.screenX,w[z+2]=m.screenY,w[z+3]=m.clientX,w[z+4]=m.clientY,w[z+5]=m.pageX,w[z+6]=m.pageY,w[z+7]=m.Ge,w[z+8]=m.Ie,w[z+9]=m.clientX-Pa.left,w[z+10]=m.clientY-Pa.top,z+=13,31<++Qa)break;w[r+8>>2]=Qa;G(d)(e,r,b)&&g.preventDefault()},ge:c})},Id=(a,b,c)=>{var d=xc[1];uc||(uc=D(8));return U({target:d,ee:"visibilitychange",he:c,ie:(e=
event)=>{var f=uc,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);w[f>>2]=document.hidden;w[f+4>>2]=g;G(c)(21,f,a)&&e.preventDefault()},ge:b})},Jd=(a,b,c,d)=>{vc||(vc=D(104));return U({target:a,oe:!0,ee:"wheel",he:d,ie:(e=event)=>{var f=vc;Dd(f,e,a);A[f+72>>3]=e.deltaX;A[f+80>>3]=e.deltaY;A[f+88>>3]=e.deltaZ;w[f+96>>2]=e.deltaMode;G(d)(9,f,b)&&e.preventDefault()},ge:c})},Kd={},Td=()=>{if(!Ld){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",
LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Kd)void 0===Kd[b]?delete a[b]:a[b]=Kd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ld=c}return Ld},Ld,Ud=[null,[],[]];h.requestFullscreen=(a,b)=>qb(a,b);h.requestAnimationFrame=a=>Ta(a);h.setCanvasSize=(a,b,c)=>{sb(h.canvas,a,b);c||tb()};h.pauseMainLoop=()=>{H=null;I++};h.resumeMainLoop=()=>{I++;var a=Ka,b=La,c=Ma;Ma=null;ab(c,0,!1,Va,!0);Ua(a,b);H()};
h.getUserMedia=()=>{window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=(a,b,c,d)=>jb(a,b,c,d);for(var K,Y=0;32>Y;++Y)Vc.push(Array(Y));var Vd=new Float32Array(288);for(Y=0;288>Y;++Y)X[Y]=Vd.subarray(0,Y+1);var Wd=new Int32Array(288);for(Y=0;288>Y;++Y)rd[Y]=Wd.subarray(0,Y+1);
var Yd={_:function(){return 0},Za:function(){return 0},_a:function(){},$a:()=>!0,Ia:a=>{if(12448==a)return L=12288,1;L=12300;return 0},La:(a,b,c,d,e)=>{if(62E3!=a)L=12296,c=0;else{if(b)for(;;){a=w[b>>2];if(12321==a)M.alpha=0<w[b+4>>2];else if(12325==a)M.depth=0<w[b+4>>2];else if(12326==a)M.stencil=0<w[b+4>>2];else if(12337==a)a=w[b+4>>2],M.antialias=0<a;else if(12338==a)a=w[b+4>>2],M.antialias=1==a;else if(12544==a)M.jf=12547!=w[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(w[e>>2]=1),c&&0<d&&
(w[c>>2]=62002),L=12288,c=1):(L=12300,c=0)}return c},ya:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;for(a=1;;){b=w[d>>2];if(12440==b)a=w[d+4>>2];else if(12344==b)break;else return L=12292,0;d+=8}if(2!=a)return L=12293,0;M.He=a-1;M.kf=0;Bb=lb(h.canvas,M);if(0!=Bb)return L=12288,mb(Bb),h.bf=!0,gb.forEach(function(e){e()}),mb(null),62004;L=12297;return 0},Aa:(a,b)=>{if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;L=12288;return 62006},za:(a,b)=>{if(62E3!=a)return L=12296,0;if(62004!=b)return L=
12294,0;a=Bb;Rb===J[a]&&(Rb=null);if("object"==typeof jc)for(var c=J[a].le.canvas,d=0;d<S.length;++d)S[d].target!=c||ac(d--);J[a]&&J[a].le.canvas&&(J[a].le.canvas.ne=void 0);J[a]=null;L=12288;xb==b&&(xb=0);return 1},Ba:(a,b)=>{if(62E3!=a)return L=12296,0;if(62006!=b)return L=12301,1;yb==b&&(yb=0);zb==b&&(zb=0);L=12288;return 1},Ma:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;if(!d)return L=12300,0;L=12288;switch(c){case 12320:return w[d>>2]=M.alpha?32:24,1;case 12321:return w[d>>
2]=M.alpha?8:0,1;case 12322:return w[d>>2]=8,1;case 12323:return w[d>>2]=8,1;case 12324:return w[d>>2]=8,1;case 12325:return w[d>>2]=M.depth?24:0,1;case 12326:return w[d>>2]=M.stencil?8:0,1;case 12327:return w[d>>2]=12344,1;case 12328:return w[d>>2]=62002,1;case 12329:return w[d>>2]=0,1;case 12330:return w[d>>2]=4096,1;case 12331:return w[d>>2]=16777216,1;case 12332:return w[d>>2]=4096,1;case 12333:return w[d>>2]=0,1;case 12334:return w[d>>2]=0,1;case 12335:return w[d>>2]=12344,1;case 12337:return w[d>>
2]=M.antialias?4:0,1;case 12338:return w[d>>2]=M.antialias?1:0,1;case 12339:return w[d>>2]=4,1;case 12340:return w[d>>2]=12344,1;case 12341:case 12342:case 12343:return w[d>>2]=-1,1;case 12345:case 12346:return w[d>>2]=0,1;case 12347:return w[d>>2]=0,1;case 12348:return w[d>>2]=1;case 12349:case 12350:return w[d>>2]=0,1;case 12351:return w[d>>2]=12430,1;case 12352:return w[d>>2]=4,1;case 12354:return w[d>>2]=0,1;default:return L=12292,0}},Q:()=>{L=12288;return 62E3},xa:()=>L,Ja:(a,b,c)=>{if(62E3!=
a)return L=12296,0;b&&(w[b>>2]=1);c&&(w[c>>2]=4);wb=!0;L=12288;return 1},Ca:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;if(0!=d&&62004!=d)return L=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return L=12301,0;mb(d?Bb:null);xb=d;zb=b;yb=c;L=12288;return 1},wa:(a,b)=>{if(62E3!=a)return L=12296,0;L=12288;if(Ab[b])return Ab[b];switch(b){case 12371:a=R("Emscripten");break;case 12372:a=R("1.4 Emscripten EGL");break;case 12373:a=R("");break;case 12429:a=R("OpenGL_ES");break;default:return L=12300,0}return Ab[b]=
a},Da:()=>{if(wb)if(h.je)if(h.je.isContextLost())L=12302;else return L=12288,1;else L=12290;else L=12289;return 0},Ea:(a,b)=>{if(62E3!=a)return L=12296,0;0==b?Ua(0,0):Ua(1,b);L=12288;return 1},Ka:a=>{if(62E3!=a)return L=12296,0;zb=yb=xb=0;wb=!1;L=12288;return 1},Ha:()=>{L=12288;return 1},Fa:()=>{L=12288;return 1},Pa:(a,b,c)=>{b=Ub(b,c);return Da[a].apply(null,b)},g:(a,b,c)=>{b=Ub(b,c);return Da[a].apply(null,b)},Lc:(a,b,c,d)=>{Vb(a?F(u,a):"",function(e){$a(function(){var f=D(e.length);u.set(e,f);
G(c)(b,f,e.length);Xd(f)})},function(){d&&$a(function(){G(d)(b)})})},$:()=>Date.now(),ra:()=>{if(!ic())return-1;cc(Gc);var a=xc[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},ua:()=>{cc(Hc);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},l:()=>devicePixelRatio,j:(a,b,c)=>{a=V(a);if(!a)return-4;a=Fc(a);A[b>>3]=a.width;A[c>>3]=a.height;return 0},T:(a,
b)=>{if(0>a||a>=kc.length)return-5;if(!kc[a])return-7;Ic(b,kc[a]);return 0},s:Ra,Oa:()=>kc.length,va:(a,b)=>{w[a>>2]=screen.width;w[b>>2]=screen.height},Nd:function(a){K.activeTexture(a)},Md:Jc,ma:(a,b)=>{K.ke.beginQueryEXT(a,P[b])},Ld:(a,b,c)=>{K.bindAttribLocation(N[a],b,c?F(u,c):"")},Kd:Kc,Id:(a,b)=>{K.bindFramebuffer(a,Hb[b])},Hd:(a,b)=>{K.bindRenderbuffer(a,Ib[b])},Gd:(a,b)=>{K.bindTexture(a,Jb[b])},ea:a=>{K.bindVertexArray(Kb[a])},Fd:function(a,b,c,d){K.blendColor(a,b,c,d)},Ed:Lc,Dd:function(a,
b){K.blendEquationSeparate(a,b)},Cd:Mc,Bd:function(a,b,c,d){K.blendFuncSeparate(a,b,c,d)},Ad:Nc,zd:(a,b,c,d)=>{K.bufferSubData(a,b,u.subarray(d,d+c))},yd:function(a){return K.checkFramebufferStatus(a)},xd:Oc,wd:Pc,vd:function(a){K.clearDepth(a)},ud:function(a){K.clearStencil(a)},td:(a,b,c,d)=>{K.colorMask(!!a,!!b,!!c,!!d)},sd:Qc,rd:(a,b,c,d,e,f,g,m)=>{K.compressedTexImage2D(a,b,c,d,e,f,m?u.subarray(m,m+g):null)},qd:(a,b,c,d,e,f,g,m,n)=>{K.compressedTexSubImage2D(a,b,c,d,e,f,g,n?u.subarray(n,n+m):
null)},pd:function(a,b,c,d,e,f,g,m){K.copyTexImage2D(a,b,c,d,e,f,g,m)},od:function(a,b,c,d,e,f,g,m){K.copyTexSubImage2D(a,b,c,d,e,f,g,m)},nd:Rc,md:Sc,ld:function(a){K.cullFace(a)},kd:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Gb[d];e&&(K.deleteBuffer(e),e.name=0,Gb[d]=null)}},jd:(a,b)=>{for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=Hb[d];e&&(K.deleteFramebuffer(e),e.name=0,Hb[d]=null)}},id:Tc,pa:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=P[d];e&&(K.ke.deleteQueryEXT(e),P[d]=null)}},hd:(a,b)=>
{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Ib[d];e&&(K.deleteRenderbuffer(e),e.name=0,Ib[d]=null)}},gd:a=>{if(a){var b=O[a];b?(K.deleteShader(b),O[a]=null):Q(1281)}},fd:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Jb[d];e&&(K.deleteTexture(e),e.name=0,Jb[d]=null)}},da:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2];K.deleteVertexArray(Kb[d]);Kb[d]=null}},dd:function(a){K.depthFunc(a)},cd:a=>{K.depthMask(!!a)},bd:function(a,b){K.depthRange(a,b)},ad:(a,b)=>{K.detachShader(N[a],O[b])},$c:Uc,_c:a=>
{K.disableVertexAttribArray(a)},Zc:(a,b,c)=>{K.drawArrays(a,b,c)},Qd:(a,b,c,d)=>{K.drawArraysInstanced(a,b,c,d)},Rd:(a,b)=>{for(var c=Vc[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];K.drawBuffers(c)},Yc:Wc,Pd:(a,b,c,d,e)=>{K.drawElementsInstanced(a,b,c,d,e)},Xc,Wc:Yc,la:a=>{K.ke.endQueryEXT(a)},Vc:function(){K.finish()},Uc:function(){K.flush()},Tc:(a,b,c,d)=>{K.framebufferRenderbuffer(a,b,c,Ib[d])},Sc:(a,b,c,d,e)=>{K.framebufferTexture2D(a,b,c,Jb[d],e)},Rc:function(a){K.frontFace(a)},Qc:$c,Oc:(a,b)=>{Zc(a,b,"createFramebuffer",
Hb)},qa:(a,b)=>{for(var c=0;c<a;c++){var d=K.ke.createQueryEXT();if(!d){for(Q(1282);c<a;)w[b+4*c++>>2]=0;break}var e=Ob(P);d.name=e;P[e]=d;w[b+4*c>>2]=e}},Nc:(a,b)=>{Zc(a,b,"createRenderbuffer",Ib)},Mc:(a,b)=>{Zc(a,b,"createTexture",Jb)},Td:function(a,b){Zc(a,b,"createVertexArray",Kb)},Pc:function(a){K.generateMipmap(a)},Kc:(a,b,c,d,e,f,g)=>{ad("getActiveAttrib",a,b,c,d,e,f,g)},Jc:(a,b,c,d,e,f,g)=>{ad("getActiveUniform",a,b,c,d,e,f,g)},Ic:(a,b,c,d)=>{a=K.getAttachedShaders(N[a]);var e=a.length;e>
b&&(e=b);w[c>>2]=e;for(b=0;b<e;++b)w[d+4*b>>2]=O.indexOf(a[b])},Hc:bd,Gc:(a,b)=>{cd(a,b,4)},Fc:(a,b,c)=>{c?w[c>>2]=K.getBufferParameter(a,b):Q(1281)},Ec:()=>{var a=K.getError()||Nb;Nb=0;return a},Dc:(a,b)=>{cd(a,b,2)},Cc:(a,b,c,d)=>{a=K.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;w[d>>2]=a},Bc:(a,b)=>{cd(a,b,0)},yc:dd,zc:ed,ga:fd,ia:gd,fa:fd,ha:gd,ja:(a,b,c)=>{c?w[c>>2]=K.ke.getQueryEXT(a,b):Q(1281)},xc:(a,b,c)=>{c?w[c>>2]=K.getRenderbufferParameter(a,
b):Q(1281)},vc:(a,b,c,d)=>{a=K.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,d,b):0;c&&(w[c>>2]=b)},uc:(a,b,c,d)=>{a=K.getShaderPrecisionFormat(a,b);w[c>>2]=a.rangeMin;w[c+4>>2]=a.rangeMax;w[d>>2]=a.precision},tc:(a,b,c,d)=>{if(a=K.getShaderSource(O[a]))b=0<b&&d?E(a,d,b):0,c&&(w[c>>2]=b)},wc:(a,b,c)=>{c?35716==b?(a=K.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=K.getShaderSource(O[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=K.getShaderParameter(O[a],
b):Q(1281)},sc:a=>{var b=Lb[a];if(!b){switch(a){case 7939:b=K.getSupportedExtensions()||[];b=b.concat(b.map(d=>"GL_"+d));b=R(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=K.getParameter(a))||Q(1280);b=b&&R(b);break;case 7938:b=R("OpenGL ES 2.0 ("+K.getParameter(7938)+")");break;case 35724:b=K.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=R(b);break;default:Q(1280)}Lb[a]=
b}return b},rc:(a,b,c)=>{c?y[c>>2]=K.getTexParameter(a,b):Q(1281)},qc:(a,b,c)=>{c?w[c>>2]=K.getTexParameter(a,b):Q(1281)},nc:kd,pc:(a,b,c)=>{ld(a,b,c,2)},oc:(a,b,c)=>{ld(a,b,c,0)},kc:(a,b,c)=>{c?w[c>>2]=K.getVertexAttribOffset(a,b):Q(1281)},mc:(a,b,c)=>{md(a,b,c,2)},lc:(a,b,c)=>{md(a,b,c,5)},jc:function(a,b){K.hint(a,b)},ic:a=>(a=Gb[a])?K.isBuffer(a):0,hc:function(a){return K.isEnabled(a)},gc:a=>(a=Hb[a])?K.isFramebuffer(a):0,fc:a=>(a=N[a])?K.isProgram(a):0,oa:a=>(a=P[a])?K.ke.isQueryEXT(a):0,ec:a=>
(a=Ib[a])?K.isRenderbuffer(a):0,dc:a=>(a=O[a])?K.isShader(a):0,cc:a=>(a=Jb[a])?K.isTexture(a):0,Sd:a=>(a=Kb[a])?K.isVertexArray(a):0,bc:function(a){K.lineWidth(a)},ac:nd,$b:(a,b)=>{3317==a&&(Mb=b);K.pixelStorei(a,b)},_b:function(a,b){K.polygonOffset(a,b)},ka:(a,b)=>{K.ke.queryCounterEXT(P[a],b)},Zb:(a,b,c,d,e,f,g)=>{(g=od(f,e,c,d,g))?K.readPixels(a,b,c,d,e,f,g):Q(1280)},Yb:()=>{},Wb:function(a,b,c,d){K.renderbufferStorage(a,b,c,d)},Vb:(a,b)=>{K.sampleCoverage(a,!!b)},Ub:function(a,b,c,d){K.scissor(a,
b,c,d)},Tb:()=>{Q(1280)},Sb:pd,Rb:function(a,b,c){K.stencilFunc(a,b,c)},Qb:function(a,b,c,d){K.stencilFuncSeparate(a,b,c,d)},Pb:function(a){K.stencilMask(a)},Ob:function(a,b){K.stencilMaskSeparate(a,b)},Nb:function(a,b,c){K.stencilOp(a,b,c)},Mb:function(a,b,c,d){K.stencilOpSeparate(a,b,c,d)},Lb:(a,b,c,d,e,f,g,m,n)=>{K.texImage2D(a,b,c,d,e,f,g,m,n?od(m,g,d,e,n):null)},Kb:function(a,b,c){K.texParameterf(a,b,c)},Jb:(a,b,c)=>{K.texParameterf(a,b,y[c>>2])},Ib:function(a,b,c){K.texParameteri(a,b,c)},Hb:(a,
b,c)=>{K.texParameteri(a,b,w[c>>2])},Gb:(a,b,c,d,e,f,g,m,n)=>{var r=null;n&&(r=od(m,g,e,f,n));K.texSubImage2D(a,b,c,d,e,f,g,m,r)},Fb:qd,Eb:(a,b,c)=>{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);K.uniform1fv(W(a),d)},Db:(a,b)=>{K.uniform1i(W(a),b)},Cb:(a,b,c)=>{if(288>=b)for(var d=rd[b-1],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);K.uniform1iv(W(a),d)},Bb:(a,b,c)=>{K.uniform2f(W(a),b,c)},Ab:(a,b,c)=>{if(144>=b)for(var d=X[2*b-1],e=0;e<
2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);K.uniform2fv(W(a),d)},zb:(a,b,c)=>{K.uniform2i(W(a),b,c)},yb:(a,b,c)=>{if(144>=b)for(var d=rd[2*b-1],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);K.uniform2iv(W(a),d)},xb:sd,wb:(a,b,c)=>{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);K.uniform3fv(W(a),d)},vb:(a,b,c,d)=>{K.uniform3i(W(a),
b,c,d)},ub:(a,b,c)=>{if(96>=b)for(var d=rd[3*b-1],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);K.uniform3iv(W(a),d)},tb:(a,b,c,d,e)=>{K.uniform4f(W(a),b,c,d,e)},sb:(a,b,c)=>{if(72>=b){var d=X[4*b-1],e=y;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=y.subarray(c>>2,c+16*b>>2);K.uniform4fv(W(a),d)},rb:(a,b,c,d,e)=>{K.uniform4i(W(a),b,c,d,e)},qb:(a,b,c)=>{if(72>=b)for(var d=rd[4*b-
1],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);K.uniform4iv(W(a),d)},pb:(a,b,c,d)=>{if(72>=b)for(var e=X[4*b-1],f=0;f<4*b;f+=4)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2];else e=y.subarray(d>>2,d+16*b>>2);K.uniformMatrix2fv(W(a),!!c,e)},ob:(a,b,c,d)=>{if(32>=b)for(var e=X[9*b-1],f=0;f<9*b;f+=9)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+
(4*f+12)>>2],e[f+4]=y[d+(4*f+16)>>2],e[f+5]=y[d+(4*f+20)>>2],e[f+6]=y[d+(4*f+24)>>2],e[f+7]=y[d+(4*f+28)>>2],e[f+8]=y[d+(4*f+32)>>2];else e=y.subarray(d>>2,d+36*b>>2);K.uniformMatrix3fv(W(a),!!c,e)},nb:td,mb:ud,lb:a=>{K.validateProgram(N[a])},kb:function(a,b){K.vertexAttrib1f(a,b)},jb:(a,b)=>{K.vertexAttrib1f(a,y[b>>2])},ib:function(a,b,c){K.vertexAttrib2f(a,b,c)},hb:(a,b)=>{K.vertexAttrib2f(a,y[b>>2],y[b+4>>2])},gb:function(a,b,c,d){K.vertexAttrib3f(a,b,c,d)},fb:(a,b)=>{K.vertexAttrib3f(a,y[b>>2],
y[b+4>>2],y[b+8>>2])},eb:function(a,b,c,d,e){K.vertexAttrib4f(a,b,c,d,e)},db:(a,b)=>{K.vertexAttrib4f(a,y[b>>2],y[b+4>>2],y[b+8>>2],y[b+12>>2])},Od:(a,b)=>{K.vertexAttribDivisor(a,b)},cb:vd,bb:wd,q:()=>0,ab:(a,b,c)=>u.copyWithin(a,b,b+c),sa:(a,b,c)=>xd(a,{Ae:w[c>>2],ye:w[c+4>>2],We:w[c+8>>2],Re:b,re:w[c+12>>2],Ee:w[c+16>>2]}),O:(a,b)=>{a=V(a);return a?a.requestPointerLock?dc()?Hc(a):b?(bc(Hc,2,[a]),1):-2:-1:-4},Va:()=>{p("OOM")},m:a=>{eval(a?F(u,a):"")},U:()=>(kc=navigator.getGamepads?navigator.getGamepads():
navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1,t:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:yd(a,b),F:(a,b,c,d)=>zd(a,b,c,d,12,"blur"),k:Bc,o:(a,b,c)=>{a=V(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},G:(a,b,c,d)=>zd(a,b,c,d,13,"focus"),v:(a,b,c,d)=>{if(!ic())return-1;a=V(a);if(!a)return-4;Ad(a,b,c,d,"webkitfullscreenchange");return Ad(a,b,c,d,"fullscreenchange")},S:(a,b,c)=>navigator.getGamepads||navigator.webkitGetGamepads?Bd(a,b,c,26,
"gamepadconnected"):-1,R:(a,b,c)=>navigator.getGamepads||navigator.webkitGetGamepads?Bd(a,b,c,27,"gamepaddisconnected"):-1,z:(a,b,c,d)=>Cd(a,b,c,d,2,"keydown"),w:(a,b,c,d)=>Cd(a,b,c,d,1,"keypress"),y:(a,b,c,d)=>Cd(a,b,c,d,3,"keyup"),Qa:(a,b,c)=>{a=G(a);ab(a,b,c)},M:(a,b,c,d)=>Ed(a,b,c,d,5,"mousedown"),K:(a,b,c,d)=>Ed(a,b,c,d,33,"mouseenter"),J:(a,b,c,d)=>Ed(a,b,c,d,34,"mouseleave"),N:(a,b,c,d)=>Ed(a,b,c,d,8,"mousemove"),L:(a,b,c,d)=>Ed(a,b,c,d,6,"mouseup"),A:(a,b,c,d)=>{if(!document||!document.body||
!(document.body.requestPointerLock||document.body.se||document.body.Ve||document.body.Se))return-1;a=V(a);if(!a)return-4;Fd(a,b,c,d,"mozpointerlockchange");Fd(a,b,c,d,"webkitpointerlockchange");Fd(a,b,c,d,"mspointerlockchange");return Fd(a,b,c,d,"pointerlockchange")},r:(a,b,c,d)=>Gd(a,b,c,d),B:(a,b,c,d)=>Hd(a,b,c,d,25,"touchcancel"),D:(a,b,c,d)=>Hd(a,b,c,d,23,"touchend"),C:(a,b,c,d)=>Hd(a,b,c,d,24,"touchmove"),E:(a,b,c,d)=>Hd(a,b,c,d,22,"touchstart"),u:(a,b,c)=>Id(a,b,c),H:(a,b,c,d)=>(a=V(a))?"undefined"!=
typeof a.onwheel?Jd(a,b,c,d):-1:-4,ta:a=>document.title=a?F(u,a):"",p:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Wa:(a,b)=>{var c=0;Td().forEach((d,e)=>{var f=b+c;e=x[a+4*e>>2]=f;for(f=0;f<d.length;++f)t[e++>>0]=d.charCodeAt(f);t[e>>0]=0;c+=d.length+1});return 0},Xa:(a,b)=>{var c=Td();x[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);x[b>>2]=d;return 0},Y:()=>52,Ya:()=>52,Ua:function(){return 70},Z:(a,b,c,d)=>{for(var e=
0,f=0;f<c;f++){var g=x[b>>2],m=x[b+4>>2];b+=8;for(var n=0;n<m;n++){var r=u[g+n],v=Ud[a];0===r||10===r?((1===a?fa:l)(F(v,0)),v.length=0):v.push(r)}e+=m}x[d>>2]=e;return 0},ca:Jc,a:Kc,Sa:Lc,Ta:Mc,b:Nc,Xb:Oc,Ra:Pc,x:Qc,na:Rc,P:Sc,Ga:Tc,W:Uc,i:Wc,X:Xc,e:Yc,c:$c,ba:bd,Na:dd,V:ed,n:kd,Jd:nd,I:pd,aa:qd,d:sd,h:td,ed:ud,f:vd,Ac:wd},Z=function(){function a(c){Z=c.exports;ia=Z.Ud;c=ia.buffer;h.HEAP8=t=new Int8Array(c);h.HEAP16=ka=new Int16Array(c);h.HEAPU8=u=new Uint8Array(c);h.HEAPU16=la=new Uint16Array(c);
h.HEAP32=w=new Int32Array(c);h.HEAPU32=x=new Uint32Array(c);h.HEAPF32=y=new Float32Array(c);h.HEAPF64=A=new Float64Array(c);Ia=Z.Zd;na.unshift(Z.Vd);B--;h.monitorRunDependencies&&h.monitorRunDependencies(B);0==B&&(null!==sa&&(clearInterval(sa),sa=null),ta&&(c=ta,ta=null,c()));return Z}var b={a:Yd};B++;h.monitorRunDependencies&&h.monitorRunDependencies(B);if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return l(`Module.instantiateWasm callback failed with error: ${c}`),!1}za(b,function(c){a(c.instance)});
return{}}(),D=a=>(D=Z.Wd)(a),Xd=a=>(Xd=Z.Xd)(a),Zd=h._main=(a,b)=>(Zd=h._main=Z.Yd)(a,b),Wb=()=>(Wb=Z._d)(),Xb=a=>(Xb=Z.$d)(a),yc=a=>(yc=Z.ae)(a);h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=Z.be)(a,b,c,d,e);h.dynCall_ji=(a,b)=>(h.dynCall_ji=Z.ce)(a,b);h.___start_em_js=87584;h.___stop_em_js=87633;var $d;ta=function ae(){$d||be();$d||(ta=ae)};
function ce(a=[]){var b=Zd;a.unshift(ca);var c=a.length,d=yc(4*(c+1)),e=d;a.forEach(g=>{x[e>>2]=zc(g);e+=4});x[e>>2]=0;try{var f=b(c,d);db(f)}catch(g){bb(g)}}
function be(){var a=ba;function b(){if(!$d&&($d=!0,h.calledRun=!0,!q)){Ga(na);Ga(oa);if(h.onRuntimeInitialized)h.onRuntimeInitialized();de&&ce(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();qa.unshift(c)}Ga(qa)}}if(!(0<B)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)ra();Ga(ma);0<B||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},
1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var de=!0;h.noInitialRun&&(de=!1);be();
